
/* ============ helpers ============ */
const r1=n=>Math.round(n*10)/10;
const r2=n=>Math.round(n*100)/100;
const num=n=>{const v=Math.round(n*100)/100;return (v%1===0)?String(v):String(v).replace(/0$/,'');};
function frac(n){ // 錠劑：四捨五入到 1/4
  const q=Math.round(n*4)/4, w=Math.floor(q), f=q-w;
  const m={0:'',0.25:'¼',0.5:'½',0.75:'¾'}[f];
  if(q===0) return '0';
  return (w?w:'')+m;
}
const mL=n=>num(r1(n))+' mL';
/* 小容量抽取（針劑分裝）用 2 位小數 —— 0.16 與 0.24 mL 在 1 位小數下會併成同一個數字 */
const mL2=n=>num(r2(n))+' mL';
/* mg/kg 對照：3 位小數去尾零 —— 2 位時 0.151 會顯示成 0.15，與「超過 0.15」的敘述打架 */
const MGKG=n=>n.toFixed(3).replace(/0+$/,'').replace(/\.$/,'')+' mg/kg';
const MG=n=>(n>=10?num(r1(n)):num(r2(n)))+' mg';
const TB=n=>{const q=Math.round(n*4)/4; return frac(n)+' #'+(Math.abs(q-n)>0.005?' <small>('+num(r2(n))+')</small>':'');};
const G=n=>num(r1(n))+' g';
/* 包裝劑：帶入 g/包，回傳四捨五入到 1/4 包的包數，並附上實際克數以便分包 */
const PK=(g,per)=>{const n=g/per,q=Math.round(n*4)/4;
  return frac(n)+' 包'+(Math.abs(q-n)>0.005?' <small>('+num(r2(n))+')</small>':'');};
const rng=(a,b)=>a===b?a:a+' ~ '+b;

/* line builders */
const L=(lbl,big,freq,flag)=>({lbl,big,freq,flag});
/* S = 附註列。藍色大字只留給實際要 key 上去的數字，
   成分拆解、換算對照這類輔助資訊用 S，以小字灰字附在主劑量下方。 */
const S=(lbl,big,freq,flag)=>({lbl,big,freq,flag,sub:1});

/* ============ DATA ============ */
const DATA=[
{c:'退燒 Antipyretics',k:'發燒 fever 退燒 antipyretic',d:[
 {n:'Voren (diclofenac) 12.5 mg 栓劑',rt:'栓劑',s:'diclofenac sodium 12.5 mg/顆｜PR｜>39°C 使用',f:'(BW/12.5) 顆',
  w:'台灣非炎栓劑仿單為「1 歲以上每日 0.5–2 mg/kg，分 2–3 次」，3 mg/kg/day 僅限幼年型類風濕性關節炎。<b>Q6H 一日 4 次 = 4 mg/kg/day 會超過仿單上限</b>，故採 <b>Q8H PRN、一日最多 3 次</b>。<b>&lt;1 歲無核准劑量</b>。',
  m:['<b>Max</b> 1 顆/dose；一日最多 3 次（≤3 mg/kg/day）','一般開 3–5 顆回家',
     '註：下方 Diclofenac 單次 PK 卡片的栓劑劑量為 <b>0.5 mg/kg</b>，與此處 1 mg/kg/dose 不一致，退燒情境用低劑量即可'],
  r:[['非炎栓劑仿單','https://kb.commonhealth.com.tw/drugs/8029.html'],['Voren 12.5mg supp 處方集','https://www.happybirth.com.tw/電子處方集/塞劑108.0410/Voren%2012.5mg%20supp-110.07.26.pdf']],
  calc:bw=>{const x=bw/12.5,cap=Math.min(x,1);return[L('每次劑量',TB(cap),'Q8H PRN（一日最多 3 次）',x>1?'已達單次上限 1 顆':null),
   L('每日上限',MG(Math.min(cap*12.5*3,3*bw)),'≤3 mg/kg/day',null)]}},
 {n:'Anti-phen (acetaminophen) 糖漿',s:'acetaminophen 24 mg/mL｜>38.5°C',f:'(BW/2) mL',
  m:['<b>Max</b> 20 mL/dose','≈12 mg/kg/dose'],
  calc:bw=>{const x=bw/2,cap=Math.min(x,20);return[L('每次劑量',mL(cap),'Q6H PRN',x>20?'已達單次上限 20 mL':null)]}},
 {n:'Sconin (ibuprofen) 糖漿',s:'ibuprofen 20 mg/mL｜60 mL/btl',f:'(BW/2) mL',
  wm:'10 mg/kg + Q6H 一日 4 次即撞到 <b>40 mg/kg/day</b> 天花板，PRN 情境無餘裕。建議 <b>Q6–8H、一日最多 4 次</b>。<b>&lt;6 個月不建議</b>；脫水或持續嘔吐時避免（腎損傷風險）。',
  m:['<b>Max</b> 20 mL/dose；40 mg/kg/day','≈10 mg/kg/dose'],
  r:[['DailyMed Children\'s Motrin 標示','https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f2609308-17bf-4bcb-84b2-d17f3fd35958']],
  calc:bw=>{const x=bw/2,cap=Math.min(x,20);return[L('每次劑量',mL(cap),'Q6~8H PRN（一日最多 4 次）',x>20?'已達單次上限 20 mL':null),
   L('每日上限',MG(Math.min(40*bw,1200)),'40 mg/kg/day, ≤1.2 g',null)]}},
 {n:'Paramol (acetaminophen) 500 mg',s:'acetaminophen 500 mg/錠',f:'(BW/40) #',
  wm:'<b>24 小時最多 5 次</b>。Q4H 給滿 6 次即違規 —— 依 5 次計算，實際每日上限為 <b>62.5 mg/kg/day</b>，低於下方標示的 75。',
  m:['<b>Max</b> 1 #/dose；4 g/day','實務上限：12.5 mg/kg/dose × 5 次 = 62.5 mg/kg/day'],
  r:[['DailyMed Children\'s Tylenol 標示','https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=333f6231-3778-4c1f-9558-2afddca22c86']],
  calc:bw=>{const x=bw/40,cap=Math.min(x,1);return[L('每次劑量',TB(cap),'Q4~6H PRN（24 小時最多 5 次）',x>1?'已達單次上限 1 #':null),
   L('每日上限',MG(Math.min(62.5*bw,4000)),'62.5 mg/kg/day（5 次）, ≤4 g',null)]}},
 {n:'Ibuprofen 400 mg',s:'ibuprofen 400 mg/錠',f:'(BW/40) #',
  wm:'同 Sconin：<b>Q6–8H、一日最多 4 次</b>。脫水或持續嘔吐時避免。',
  m:['<b>Max</b> 1 #/dose；40 mg/kg/day；1.2 g/day'],
  calc:bw=>{const x=bw/40,cap=Math.min(x,1);return[L('每次劑量',TB(cap),'Q6~8H PRN（一日最多 4 次）',x>1?'已達單次上限 1 #':null),
   L('每日上限',MG(Math.min(40*bw,1200)),'40 mg/kg/day, ≤1.2 g',null)]}},
 {n:'Idefen susp',s:'ibuprofen 20 mg/mL 懸液（生達 炎熱消）｜與 Sconin 同成分同濃度',f:'(BW/3) ~ (BW/2) mL = 5~10 mg/kg',
  wm:'退燒／止痛的公認劑量是<b>範圍</b>：<b>5–10 mg/kg/dose，Q6–8H</b>（AAP／Lexicomp／FDA OTC 標示一致）。常見分流是<b>低燒用 5、≥39°C 用 10</b>。<br>因此 <b>BW/3（6.7 mg/kg）與 BW/2（10 mg/kg）都在範圍內</b>，北醫手冊在 Idefen 寫 BW/3、Sconin 寫 BW/2 並不矛盾，只是取了不同點。下方兩端並列，依發燒程度選。<b>&lt;6 個月不建議</b>；脫水或持續嘔吐時避免（腎損傷風險）。',
  m:['5–10 mg/kg/dose，Q6–8H','<b>Max</b> 20 mL/dose；40 mg/kg/day（OTC 建議 ≤30）','抗發炎適應症（如 JIA）另為 30–50 mg/kg/day'],
  calc:bw=>{const lo=Math.min(bw/3,20),hi=Math.min(bw/2,20);
   return[L('低劑量端（5 mg/kg）',mL(lo),'BW/3，一般發燒',null),
    L('高劑量端（10 mg/kg）',mL(hi),'BW/2，≥39°C',bw/2>20?'已達單次上限 20 mL':null),
    L('每日上限',MG(Math.min(40*bw,1200)),'40 mg/kg/day, ≤1.2 g',null)]}},
 {n:'Cataflam 25 mg',s:'diclofenac potassium 25 mg/糖衣錠',f:'限能吞錠者｜0.5–1 mg/kg/dose',
  wm:'台灣仿單<b>無兒童 mg/kg 劑量</b>，兒科使用屬 off-label。依 diclofenac 每日 0.5–2 mg/kg 分 2–3 次推算，25 mg 錠對<b>約 25 kg 以上</b>才切得準；小體重請改用 Voren 栓劑或 ibuprofen。同 NSAID 注意事項：脫水、嘔吐、腎功能不全時避免。',
  m:['錠劑無法準確分割，限能吞整錠者','每日總量 0.5–2 mg/kg，分 2–3 次'],
  calc:bw=>[L('每日總量參考',rng(MG(0.5*bw),MG(2*bw)),'分 2–3 次',null),
   L('換算 25 mg 錠',rng(num(r2(0.5*bw/25)),num(r2(2*bw/25)))+' #','每日',2*bw<12.5?'每日量不足半錠，此劑型不適合':null)]},
 {n:'Diclofenac 單次劑量參考',s:'diclofenac｜1–12 歲，AUC 等同成人 50 mg',f:'IV 0.3 / PR 0.5 / PO 1 mg/kg',
  m:['Ref: <a href="https://pubmed.ncbi.nlm.nih.gov/21276131/" target="_blank">PMID 21276131</a>'],
  calc:bw=>[L('IV',MG(0.3*bw),'單次',null),L('栓劑',MG(0.5*bw),'單次',null),L('口服',MG(1*bw),'單次',null)]},
]},

{c:'止咳 Antitussive',k:'咳嗽 cough',d:[
 {n:'Cough mixture',s:'院內自配方，成分未列｜120 mL/btl',f:'(BW/4) mL',
  wm:'<b>院內自配方，成分未列</b>。無成分表就無法核 mg/kg，也無法判斷是否與 Secorine 或抗組織胺重複。開立前請先確認院內配方組成。',
  m:['<b>Max</b> 10 mL/dose','= 1 mL/kg/day'],
  calc:bw=>{const x=bw/4,cap=Math.min(x,10);return[L('每次劑量',mL(cap),'QID',x>10?'已達單次上限 10 mL':null)]}},
 {n:'Secorine',s:'methylephedrine 1 + chlorpheniramine 0.1 + guaifenesin 5 mg/mL｜息咳寧糖漿',f:'1~2 mL/kg/day（中國醫）',
  w:'<b>三合一複方，內含第一代抗組織胺 chlorpheniramine</b>。與 Peace syrup、Cypromin 或任何抗組織胺併用會造成<b>重複給藥</b>；與 Peace 併用另有擬交感神經藥疊加（methylephedrine + pseudoephedrine）。',
  m:['<b>仿單</b> 3–6 y：2.5 mL TID~QID','6–12 y：5 mL TID~QID','成人：10 mL TID~QID'],
  calc:bw=>[L('每日總量',rng(mL(bw),mL(2*bw)),'分 3~4 次',null)]},
 {n:'Medicon-A 15 mg',s:'dextromethorphan HBr 15 mg/錠｜滅咳康',f:'1 # TID（6–12 y）｜1–2 # TID（>12 y）',
  wm:'同 Mephan 之成分，僅規格不同（15 vs 30 mg），<b>兩者勿並用</b>。FDA 標示 <b>&lt;4 歲不得使用</b>；諮詢委員會建議 &lt;6 歲不用。6–12 歲 15 mg TID = 45 mg/day，未超過 60 mg/day 上限 ✅',
  m:['固定劑量，不依體重','<b>Max</b> 60 mg/day（6–12 y）'],
  r:[['FDA 兒童止咳感冒藥','https://www.fda.gov/drugs/special-features/use-caution-when-giving-cough-and-cold-products-kids']],calc:null},
 {n:'Mephan 30 mg',s:'dextromethorphan 30 mg/錠',f:'0.5 # TID（6–12 y）',
  wm:'FDA 標示 <b>&lt;4 歲不得使用</b>；諮詢委員會建議 <b>&lt;6 歲不用</b>。6–12 y 15 mg TID = 45 mg/day，未超過 60 mg/day 上限 ✅',
  m:['固定劑量，不依體重'],
  r:[['FDA 兒童止咳感冒藥','https://www.fda.gov/drugs/special-features/use-caution-when-giving-cough-and-cold-products-kids']],calc:null},
]},

{c:'化痰 Mucolytic',k:'痰 phlegm mucolytic',d:[
 {n:'Soltan liquid',s:'ambroxol 3 mg/mL',f:'(BW×0.15) mL QID 或 (BW×0.2) mL TID',
  w:'<b>&lt;2 歲禁用</b>（幼兒排痰能力不足，有呼吸道阻塞風險）。<b>2–6 歲此公式會高出仿單 2–3 倍</b> —— 4 歲 15 kg 算出 27 mg/day，仿單為 7.5–11.25 mg/day。該年齡層請改以年齡劑量封頂（2–6 y：7.5 mg BID~TID）。6 歲以上公式適用 ✅',
  m:['= 0.6 mL/kg/day（≈1.8 mg/kg/day）'],
  calc:bw=>[L('QID 用法',mL(0.15*bw),'QID（限 >6 歲）',null),L('TID 用法',mL(0.2*bw),'TID（限 >6 歲）',null),
   L('2–6 歲固定劑量','2.5 mL','BID ~ TID（依仿單，勿用上方公式）',null)]},
 {n:'Actein 600 mg',s:'acetylcysteine 600 mg/發泡錠｜>6 y 可用',f:'1 # QD（6–12 y）｜QD~BID（>12 y）',
  wm:'台灣仿單允許 >6 歲 1 錠 QD–BID，但<b>歐洲 SmPC 成人上限為 600 mg/day</b>。6–12 歲建議以 <b>QD</b> 為主。<b>&lt;2 歲禁用</b>。',
  m:['固定劑量，不依體重'],calc:null},
 {n:'Bisolvon liq',s:'bromhexine HCl 2 mg/mL 內服液',f:'依年齡（非體重換算）',
  wm:'手冊把 Bisolvon 列在「蒸氣」欄，但台灣許可證為 <b>內服液劑</b>（另有錠劑），<b>非吸入劑型</b> —— 請核對院內實際品項。仿單依年齡給藥：2–5 歲 2 mg TID；6–11 歲 4 mg TID；&gt;12 歲 8 mg TID。<b>&lt;2 歲不建議</b>。療效證據薄弱，歐盟已限縮適應症。',
  m:['2–5 y：1 mL (2 mg) TID','6–11 y：2 mL (4 mg) TID','>12 y：4 mL (8 mg) TID'],
  calc:bw=>[L('2–5 歲','1 mL','TID（= 2 mg）',null),L('6–11 歲','2 mL','TID（= 4 mg）',null),L('>12 歲','4 mL','TID（= 8 mg）',null)]},
 {n:'Actein 粉劑',s:'acetylcysteine 200 mg/pk（北醫小包裝，2026-08 確認）',f:'(BW/40) 包 = 5 mg/kg/dose',
  wm:'<b>規格已確認為 200 mg/pk，(BW/40) 包 = 5 mg/kg/dose 正確 ✅</b>（先前因院內規格未定而標為待核，已解除）。<br>若他院使用 <b>100 mg/包</b> 規格，同一公式只會給到應給量的一半，換院區或代訓時請重新核對。<b>&lt;2 歲禁用</b>（幼兒排痰能力不足，有呼吸道阻塞風險）。',
  m:['200 mg/pk × (BW/40) 包 = 5 mg/kg/dose','他院若為 100 mg/包，劑量減半，須改算'],
  calc:bw=>[L('每次劑量',num(r2(bw/40))+' 包','TID ~ QID',null),
   S('= mg',MG(5*bw),'（200 mg/pk 換算）')]},
]},

{c:'鼻塞流鼻水 Antihistamine',k:'鼻塞 流鼻水 過敏 rhinitis antihistamine',d:[
 {n:'Peace syrup',s:'triprolidine 0.25 + pseudoephedrine 6 mg/mL（Actifed 型）｜60 mL/btl',f:'(BW×0.2) mL',
  w:'<b>含 pseudoephedrine 的複方，非單純抗組織胺</b>。FDA：<b>&lt;2 歲禁用</b>複方止咳感冒藥、<b>&lt;4 歲標示不得使用</b>。與 Secorine 併用會造成擬交感神經藥＋抗組織胺雙重疊加。食藥署 2025/7/31 再評估公告，要求 2026/5/31 前完成中文仿單修訂（新增 PRES/RCVS 等中樞血管警語）。',
  m:['<b>Max</b> 2–5 y 10 mL/d；6–12 y 20 mL/d；>12 y 40 mL/d'],
  r:[['FDA 兒童止咳感冒藥','https://www.fda.gov/drugs/special-features/use-caution-when-giving-cough-and-cold-products-kids']],
  calc:bw=>{const x=0.2*bw,day=x*3;return[L('每次劑量',mL(x),'TID',null),L('每日總量',mL(day),'（對照上限）',
    day>40?'超過 >12y 上限 40 mL/d':(day>20?'已超過 6–12y 上限 20 mL/d，請依年齡核對':(day>10?'已超過 2–5y 上限 10 mL/d，請依年齡核對':null)))]}},
 {n:'Cypromin soln',s:'cyproheptadine 2 mg/5 mL｜第一代',f:'(BW×0.15) mL QID 或 (BW×0.2) mL TID',
  wm:'每日上限：<b>2–6 歲 Max 12 mg/day；7–14 歲 Max 16 mg/day</b>。<b>&lt;2 歲不建議</b>。第一代 antihistamine，注意嗜睡與抗膽鹼作用。',
  m:['= 0.24 mg/kg/day','超過年齡上限時下方會標紅'],
  calc:bw=>{const day=0.24*bw;
   return[L('QID 用法',mL(0.15*bw),'QID',null),L('TID 用法',mL(0.2*bw),'TID',null),
    L('每日總量',MG(day),'（對照年齡上限）',
     day>16?'超過 7–14 歲上限 16 mg/day':(day>12?'已超過 2–6 歲上限 12 mg/day，請依年齡核對':null))]}},
 {n:'Cetirizine soln',s:'cetirizine 1 mg/mL',f:'(BW/4) mL',
  m:['<b>Max</b> <1 y 2.5 mL/d；1–5 y 5 mL/d；>6 y 5–10 mL/d'],
  calc:bw=>{const x=bw/4;return[L('每次劑量',mL(x),'QD 或 BID',null),
   L('BID 每日量',mL(2*x),'（對照上限）',2*x>10?'超過 >6y 上限 10 mL/d':(2*x>5?'已超過 1–5y 上限 5 mL/d，請依年齡核對':null))]}},
 {n:'Allegra 60 mg',s:'fexofenadine 60 mg/錠（台灣另有 30 mg 與 6 mg/mL 懸液）',f:'0.5 # BID (6–11 y)｜1 # BID (>12 y)',
  wm:'台灣有 <b>30 mg 錠</b>與 6 mg/mL 懸液，6–11 歲請<b>優先開 30 mg 規格</b>避免分割誤差。<b>勿與果汁同服</b>（果汁降低吸收約 1/3）。',
  m:['固定劑量：30 mg BID (6–11 y)｜60 mg BID (>12 y)'],calc:null},
 {n:'Cetin',s:'抗組織胺｜<b>學名與規格待核</b>｜>6 y',f:'1 # QD',m:['固定劑量'],calc:null},
 {n:'Pilian 錠',s:'cyproheptadine 錠（永信 佩你安）｜<b>單錠含量待核</b>（一般為 4 mg）｜第一代',f:'0.25 mg/kg/day 分 2–3 次',
  wm:'與 Cypromin 同成分，僅劑型不同（錠劑 vs 2 mg/5 mL 溶液），<b>兩者勿並用</b>。每日上限同：<b>2–6 歲 Max 12 mg/day；7–14 歲 Max 16 mg/day</b>。<b>&lt;2 歲不建議</b>。第一代 antihistamine，注意嗜睡與抗膽鹼作用；<b>會刺激食慾</b>，肥胖兒童留意。',
  m:['能吞錠者用此，否則用 Cypromin 溶液','超過年齡上限時下方會標紅'],
  calc:bw=>{const day=0.24*bw;
   return[L('每日總量',MG(day),'分 2–3 次',day>16?'超過 7–14 歲上限 16 mg/day':(day>12?'已超過 2–6 歲上限 12 mg/day，請依年齡核對':null)),
    L('TID 每次',MG(day/3),'',null)]}},
 {n:'Denosin 5 mg',s:'desloratadine 5 mg/錠',f:'0.5 # QD (6–11 y)｜1 # QD (>12 y)',
  wm:'desloratadine 幾乎不引起嗜睡，<b>不必固定睡前服用</b>（寫死 HS 反而容易漏服）。QD、任何時間皆可。',
  m:['固定劑量'],calc:null},
]},

{c:'喉嚨痛 / 嘴破',k:'喉嚨痛 嘴破 口腔潰瘍 腸病毒 stomatitis',d:[
 {n:'Comfflam spray',rt:'外用',s:'benzydamine HCl 3 mg/mL 口腔噴液',f:'3~4 puff TIDAC',
  m:['腸病毒可用','$自費 250 元'],calc:null},
 {n:'Zine',rt:'外用',s:'類固醇口內膏｜<b>學名與含量待核</b>',f:'1XX HS ~ TID',m:[],calc:null},
 {n:'Mundisal',rt:'外用',s:'choline salicylate 87.1 mg/g 口內膏',f:'1XX TID',m:[],calc:null},
]},

{c:'哮吼 Croup',k:'croup 哮吼 stridor 犬吠咳',d:[
 {n:'Dexamethasone 0.5 mg / Dorison 4 mg',s:'dexamethasone 0.5 mg/錠；Dorison 4 mg/錠｜PO',f:'(BW×0.6) mg',
  wm:'<b>Max 12 mg</b>（20 kg 即封頂）。Cochrane 證實<b>口服與肌注效果相同</b>，能口服就不要打針。',
  m:['單次給藥','0.6 mg/kg，Max 12 mg'],
  r:[['Cochrane: Glucocorticoids for croup','https://www.cochrane.org/CD001955/ARI_glucocorticoids-croup-children']],
  calc:bw=>{const raw=0.6*bw,mgv=Math.min(raw,12);return[L('總劑量',MG(mgv),'PO, ONCE',raw>12?'已達上限 12 mg（算出 '+MG(raw)+'）':null),
   L('Dexa 0.5 mg 錠',TB(mgv/0.5),'',null),L('Dorison 4 mg 錠',TB(mgv/4),'',null)]}},
 {n:'Rinderon (betamethasone)',rt:'針劑',s:'betamethasone 4 mg/amp｜IM',f:'(BW×0.15~0.6) mg',
  wm:'哮吼用法屬 <b>off-label</b>（台灣仿單無兒童 mg/kg）。Cochrane 已證實口服與肌注效果相同，<b>優先口服 dexamethasone</b>。',
  m:['<b>Max</b> 10 mg'],
  calc:bw=>{const lo=Math.min(0.15*bw,10),hi=Math.min(0.6*bw,10);
   return[L('劑量範圍',rng(MG(lo),MG(hi)),'IM, ONCE',0.6*bw>10?'高端已達上限 10 mg':null),
    L('換算 amp',rng(num(r2(lo/4)),num(r2(hi/4)))+' amp','（4 mg/amp）',null)]}},
 {n:'Adrenaline (epinephrine)',rt:'吸入',s:'epinephrine 1 mg/mL (1:1000)｜1 mg/amp｜吸入',f:'(BW/2) mg IH',
  wm:'「不用稀釋」需但書：<b>體重 &lt;6 kg 時算出量 &lt;3 mL，霧化效率不足</b>，應以 N/S 稀釋至總量 3 mL。給藥後需<b>觀察 2–3 小時</b>防 rebound stridor。',
  m:['<b>Max</b> <4 y 2.5 mg；>4 y 5 mg','= 0.5 mL/kg (1:1000)'],
  calc:bw=>{const x=bw/2;return[L('劑量',MG(Math.min(x,5)),'IH',
   x>5?'已達 >4y 上限 5 mg':(x>2.5?'超過 <4y 上限 2.5 mg':null)),
   L('霧化總量',bw<6?'需以 N/S 稀釋至 3 mL':num(r1(Math.min(x,5)))+' mL（不需稀釋）','',bw<6?'體重 <6 kg，原液量不足以有效霧化':null)]}},
]},

{c:'氣喘 Asthma',k:'asthma 氣喘 喘鳴 wheeze',d:[
 {n:'Bricanyl',rt:'吸入',s:'terbutaline 吸入｜<b>規格待核</b>',f:'1 amp (>20 kg)｜0.5 amp (<20 kg)',
  wm:'兩段式分法在 <b>10 kg 幼兒偏高</b>（算出 0.25 mg/kg vs 仿單 0.2）、<b>20–25 kg 也偏高</b>。小體重與臨界體重請依仿單 mg/kg 核對。',
  m:['q20min × 3 doses，之後 Q2H–Q8H'],
  calc:bw=>[L('劑量',bw>=20?'1 amp':'0.5 amp','q20min ×3 → Q2–8H',null),
   L('實際 mg/kg',num(r2((bw>=20?5:2.5)/bw))+' mg/kg','（仿單約 0.2 mg/kg）',
    ((bw>=20?5:2.5)/bw)>0.25?'高於仿單 0.2 mg/kg 甚多，請核對':null)]},
 {n:'Meptin liq',s:'procaterol 5 µg/mL',f:'(BW/4) mL',
  m:['<b>Max</b> 5 mL BID','Meptin 25 µg：1 # BID'],
  calc:bw=>{const x=bw/4,cap=Math.min(x,5);return[L('每次劑量',mL(cap),'BID',x>5?'已達上限 5 mL':null)]}},
 {n:'Solu-medrol',rt:'針劑',s:'methylprednisolone sodium succinate｜40 / 125 / 500 mg/vial｜IV',f:'Loading 0.8–1.6 / Maint 0.2–0.4 mg/kg/dose',
  wm:'<b>Max 60 mg/24hr</b>。另注意：選 <b>Q12H + 0.2 mg/kg</b> 時每日僅 0.4 mg/kg/day，<b>低於指引下限 1 mg/kg/day</b>，也低於台灣仿單「不可低於 0.5 mg/kg/24 小時」—— 下方會標示。',
  m:['Loading = prednisolone 1–2 mg/kg/dose','Maint = prednisolone 1–2 mg/kg/day','<b>Max</b> 60 mg/24hr'],
  calc:bw=>[L('Loading',rng(MG(Math.min(0.8*bw,60)),MG(Math.min(1.6*bw,60))),'IV, STAT',1.6*bw>60?'高端已達上限 60 mg':null),
   L('Maintenance',rng(MG(0.2*bw),MG(0.4*bw)),'IV, Q6H–Q12H',null),
   L('Q12H×0.2 之日量',MG(0.4*bw),'0.4 mg/kg/day','低於指引下限 1 mg/kg/day，此組合偏低'),
   L('Q6H×0.4 之日量',MG(Math.min(1.6*bw,60)),'1.6 mg/kg/day',null)]},
 {n:'Kidsolone',s:'prednisolone 1 mg/mL',f:'Loading (BW×1–2) mL｜Maint (BW/2~BW/4) mL',
  wm:'<b>Max 60 mg/day</b>；GINA 年齡上限 &lt;2y 20／2–5y 30／5–12y 40／&gt;12y 50 mg。另：指引為 <b>QD 或 BID 即可</b>，不需 QID。',
  m:['Loading = 1–2 mg/kg/dose','Maint = 1–2 mg/kg/day','<b>Max</b> 60 mg/day'],
  r:[['GINA 2024 報告','https://ginasthma.org/2024-report/']],
  calc:bw=>[L('Loading',rng(mL(Math.min(bw,60)),mL(Math.min(2*bw,60))),'PO, STAT',2*bw>60?'高端已達上限 60 mg':null),
   L('Maintenance 每日總量',rng(mL(Math.min(bw,60)),mL(Math.min(2*bw,60))),'分 QD 或 BID',null),
   L('BID 每次量',rng(mL(Math.min(bw,60)/2),mL(Math.min(2*bw,60)/2)),'BID',null)]},
]},

{c:'腹瀉 Antidiarrheal',k:'腹瀉 拉肚子 diarrhea',d:[
 {n:'Hidrasec 10 mg',s:'racecadotril 10 mg/包（>13 kg 用 30 mg/包）',f:'1.5 mg/kg/dose TID',
  wm:'腦啡肽酶抑制劑，<b>抗分泌而不影響腸蠕動</b>，不像 loperamide 有腸阻塞與中樞風險，適合急性水瀉輔助。台灣有 10 mg（&gt;3 個月嬰幼兒）與 30 mg（&gt;13 kg）兩種規格。<b>療程勿超過 7 天</b>；<b>不可取代口服電解質液</b> —— 補液仍是主軸。&lt;3 個月不建議。',
  m:['1.5 mg/kg/dose TID','10 mg 包：<13 kg｜30 mg 包：>13 kg','療程 ≤7 天；務必併用 ORS'],
  calc:bw=>{const d=1.5*bw;
   return[L('每次劑量',MG(d),'TID',null),
    L('換算包數',bw<13?num(r2(d/10))+' 包（10 mg）':num(r2(d/30))+' 包（30 mg）','TID',null),
    L('每日總量',MG(3*d),'',null)]}},
 {n:'Smecta',s:'diosmectite 3 g/sachet',f:'依年齡',
  w:'<b>&lt;2 歲已於國際間限制使用。</b>2019–2020 起，因黏土製劑天然含鉛、幼兒血腦屏障未成熟，歐盟 ANSM/EMA、新加坡 HSA、馬來西亞 NPRA、韓國均限制 diosmectite <b>不得用於 2 歲以下</b>及孕哺婦。現行 SmPC：<b>2–5 歲 半包 TID；&gt;5 歲及成人 1 包 TID</b>。',
  m:['<b>2–5 y</b>：½ 包 TID','<b>>5 y / 成人</b>：1 包 TID','劑量依年齡，不依體重'],
  r:[['馬來西亞 NPRA 2019 安全警訊','https://www.npra.gov.my/index.php/en/component/content/article/414-english/safety-alerts-main/safety-alerts-2019/1527023-smecta-dioctahedral-smectite-not-recommended-for-use-in-children-aged-below-2-years-and-pregnant-or-breastfeeding-women.html?Itemid=1391'],['Smecta SmPC','https://assets.hpra.ie/products/Human/23784/LicenseSPC_PA1003-001-001_13042010225147.pdf']],
  calc:bw=>[L('2–5 歲','½ 包','TID',null),L('>5 歲 / 成人','1 包','TID',null),
   L('<2 歲','不建議使用','—','國際間已限制 <2 歲使用')]},
]},

{c:'便秘 Constipation',k:'便秘 constipation 灌腸 浣腸 PEG macrogol forlax 滲透性瀉劑',d:[
 {n:'Forlax 10 g',rt:'口服',s:'macrogol 4000（PEG 4000）10 g/包｜溶於 ≥50 mL 開水',f:'維持 0.4~0.8 g/kg/day',
  w:'<b>仿單與指引在此不一致，開立前請自行決定依據。</b><br>Forlax <b>10 g 包裝的仿單適應症為成人與 ≥8 歲兒童</b>，每日 1–2 包、<b>上限 2 包/日</b>，兒童療程<b>上限 3 個月</b>。ESPGHAN/NASPGHAN 2026 則採<b>體重換算</b>（維持 0.4–0.8 g/kg/day），RCT 證據涵蓋 <b>≥6 個月</b>，GDG 另有自 1 個月起的使用經驗但明言證據不足。<br><b>兩者約在 25 kg 交會</b> —— 0.8 g/kg/day 到 25 kg 即達 20 g（＝仿單上限 2 包）；體重再大者依指引換算會超出仿單上限。<br><b>兒童專用為 4 g 包裝</b>；院內若只有 10 g，幼童需分包給藥。',
  wm:'<b>嵌塞解除（disimpaction）1–1.5 g/kg/day 必然超過仿單上限</b>，指引明訂<b>最多 6 天</b>，之後改回維持劑量。ESPGHAN 該劑量表自述「僅供參考，<b>不得作為處方依據</b>，實際處方應依各國仿單與藥品許可」—— 下方換算沿用指引數字，責任在開立者。',
  m:['ESPGHAN/NASPGHAN 2026：PEG 為兒童功能性便秘<b>第一線（strong recommendation）</b>，優於 lactulose 與氫氧化鎂',
     '維持 <b>0.4–0.8 g/kg/day</b>，可 QD 或分次',
     '嵌塞解除 <b>1–1.5 g/kg/day，最多 6 天</b>',
     '<b>仿單上限 2 包/日（20 g）</b>；兒童療程上限 3 個月',
     '起效 <b>24–48 小時</b>，非即效藥；溶於 ≥50 mL 開水',
     '試驗中未見嚴重不良事件，亦<b>無證據支持神經毒性</b>疑慮；體積較大，順從性與口味需衛教'],
  r:[['ESPGHAN/NASPGHAN 2026 兒童功能性便秘指引','https://doi.org/10.1002/jpn3.70447'],['Forlax 10 g 仿單（EMC）','https://www.medicines.org.uk/emc/files/pil.3170.pdf']],
  calc:bw=>{
    const mLo=0.4*bw,mHi=0.8*bw,cLo=Math.min(mLo,20),cHi=Math.min(mHi,20);
    const dLo=bw,dHi=1.5*bw;
    return[
     L('維持劑量',rng(PK(cLo,10),PK(cHi,10)),'QD 或分次',
       mHi>20?'依體重算出 '+rng(G(mLo),G(mHi))+'，已封頂於仿單上限 2 包/日（20 g）':null),
     S('　＝每日總量',rng(G(cLo),G(cHi)),
       mHi>20?'（0.4 g/kg/day ~ 仿單上限 20 g）':'（0.4~0.8 g/kg/day）'),
     L('嵌塞解除',rng(PK(dLo,10),PK(dHi,10)),'最多 6 天，之後改維持量',
       '1~1.5 g/kg/day —— 已超出仿單上限 2 包/日，屬指引用法'),
     S('　＝每日總量',rng(G(dLo),G(dHi)),'（1~1.5 g/kg/day）')]}},
 {n:'Glycerine 甘油球 30%',rt:'灌腸',s:'glycerin 30%（<b>院內多為 50%，須核對</b>）｜10 mL/btl',f:'(BW×1~2) mL',
  wm:'台灣市售甘油球<b>多為 50%</b>（含 NaCl），非筆記所寫的 30%。請核對院內實際品項濃度。',
  m:['以 N/S 稀釋 1–2 倍','人生浣腸已稀釋：15% NaCl + 15% glycerin'],
  calc:bw=>[L('劑量',rng(mL(bw),mL(2*bw)),'PR，稀釋 1–2 倍',null)]},
 {n:'Evac 意福灌腸液',rt:'灌腸',s:'sodium phosphate monobasic 139.1 + dibasic 31.8 mg/mL｜衛署藥製字第034255號｜>2 y',f:'(BW×2.5) mL',
  w:'<b>台灣查無 Fleet enema 許可證</b>，本院對應品項為磷酸鈉灌腸液（意福 Evac、理可 Riko、意淨 Eagen 三張許可證，成分同為 monobasic + dibasic sodium phosphate）。磷酸鈉灌腸的<b>致命性高磷血症、低血鈣、抽搐、AKI</b> 風險集中在 &lt;5 歲、脫水、腎功能不全、Hirschsprung —— <b>&lt;5 歲請優先改用甘油球</b>。腎功能不佳禁用。<br><b>⚠ 劑量與濃度須自行核對</b>：2.5 mL/kg 出自 Lexicomp/AAP，是依 Fleet（約 monobasic 161 + dibasic 59 mg/mL）訂的；意福為 <b>139.1 + 31.8 mg/mL</b>，較稀，且三張許可證都<b>沒有可讀的中文仿單</b>（意福／理可無仿單檔，意淨為掃描圖）。開立前務必核對院內實際品項的濃度與瓶裝容量。',
  m:['2.5 mL/kg/dose（Lexicomp/AAP，依 Fleet 濃度）','<b>Max</b> 一瓶；下方以 Fleet 的 133 mL 暫代，須改為院內實際容量','TFDA 適應症：便秘之緩解、大腸檢查前腸道排空、腹部手術前緩下劑'],
  r:[['AAP Sodium Phosphates','https://publications.aap.org/pediatriccare/drug-monograph/18/5150/Sodium-Phosphates'],['Medscape Sodium Phosphate Enema','https://reference.medscape.com/drug/fleet-enema-pedialax-enema-sodium-phosphate-rectal-999711']],
  calc:bw=>{const x=2.5*bw,cap=Math.min(x,133);
   return[L('劑量',mL(cap),'PR',x>133?'已達 133 mL（算出 '+mL(x)+'）—— 此上限依 Fleet 瓶裝，請核對院內容量':null)]}},
 {n:'MgO 250 mg',s:'magnesium oxide 250 mg/錠',f:'(BW/20) #',
  wm:'台灣仿單「<b>每日以 3 次為限</b>」，故採 TID，不用 QID。',
  m:['腎功能不全者注意高血鎂'],calc:bw=>[L('每次劑量',TB(bw/20),'TID（每日最多 3 次）',null)]},
 {n:'Duphalac',s:'lactulose 666 mg/mL',f:'BW × 1~3 mL/day',
  m:['1–2 g/kg QD 或 BID','成人上限 40 g/day (60 mL/day)'],
  calc:bw=>{const lo=Math.min(bw,60),hi=Math.min(3*bw,60);
   return[L('每日總量',rng(mL(lo),mL(hi)),'QD 或 BID',3*bw>60?'超過 60 mL/day 上限，已封頂':null)]}},
 {n:'Gaslan 40 mg',s:'dimethicone 40 mg/錠',f:'≥2 y：1 # TID~QID（固定劑量）',
  wm:'simethicone 不經腸道吸收、幾無毒性，<b>用固定年齡劑量而非體重換算</b>：標準 ≥2 歲為 <b>40 mg/次</b>。',
  m:['≥2 y：40 mg（1 #）TID~QID','<2 y：½ # TID~QID'],
  calc:bw=>[L('≥2 歲劑量','1 #','TID ~ QID（固定劑量）',null),L('<2 歲劑量','½ #','TID ~ QID',null)]},
 {n:'Kascoal 50 mg',s:'simethicone 50 mg/錠｜<b>TFDA 同名品項為 40 mg，須核對院內規格</b>｜≥3 y',f:'1 # TID~QID',
  wm:'台灣仿單為「<b>3 歲以上 1 錠 TID–QID</b>」（上限 200 mg/day）—— 年齡門檻是 <b>3 歲</b>不是 2 歲，且非 1~2 錠。國際 OTC 上限 480 mg/day，故 200 mg/day 仍有安全餘裕。',
  m:['= Wilcon 20 mg/mL：<2 y 1 mL；>2 y 2 mL TID~QID','<b>Max</b> 200 mg/day（4 #）｜$自費'],calc:null},
 {n:'Sennoside 12 mg',s:'sennoside 12 mg/膜衣錠｜刺激性瀉劑',f:'依年齡固定劑量',
  w:'<b>刺激性瀉劑，不作兒童慢性便秘的第一線</b> —— 第一線為滲透性瀉劑（lactulose、PEG）。僅短期用於嵌塞解除或滲透性瀉劑無效時。<br>依年齡：2–6 歲 4.4 mg（⅓–½ 錠）QD HS；6–12 歲 8.6 mg（½–1 錠）QD HS；&gt;12 歲 12–24 mg（1–2 錠）QD HS。<b>&lt;2 歲不建議</b>。可致腹絞痛與電解質流失，長期使用有依賴性疑慮。',
  m:['睡前單次給藥，隔日晨間排便','短期使用，勿長期依賴','<2 歲不建議'],
  calc:bw=>[L('2–6 歲','⅓ ~ ½ #','QD HS',null),L('6–12 歲','½ ~ 1 #','QD HS',null),L('>12 歲','1 ~ 2 #','QD HS',null)]},
 {n:'Bisacodyl 栓劑',rt:'栓劑',s:'bisacodyl 5 mg（<10 y）／10 mg（>10 y）栓劑｜PR',f:'依年齡固定劑量',
  wm:'栓劑作用快（15–60 分鐘），適合<b>急性嵌塞或需快速排便</b>時。&lt;2 歲 5 mg；2–10 歲 5 mg；&gt;10 歲 10 mg，QD。同為刺激性瀉劑，<b>不作慢性便秘長期用藥</b>。肛裂或直腸黏膜受損時避免。',
  m:['<10 y：5 mg PR QD','>10 y：10 mg PR QD','作用時間 15–60 分鐘'],
  calc:bw=>[L('<10 歲','5 mg','PR QD',null),L('>10 歲','10 mg','PR QD',null)]},
 {n:'Clyster 通樂浣腸液',rt:'灌腸',s:'benzalkonium chloride + glycerin｜<b>濃度與容量依院內品項</b>',f:'依院內品項容量',
  wm:'成分為 <b>benzalkonium chloride + glycerin</b>，與甘油球同屬滲透／刺激性灌腸，<b>不含磷酸鈉</b>，故無高磷血症風險 —— 幼兒優先於磷酸鈉灌腸。實際容量與濃度依院內品項，仿單未提供兒童 mL/kg 換算，請依品項標示給藥。',
  m:['幼兒優先於磷酸鈉灌腸','無高磷血症風險','劑量依院內品項標示'],calc:null},
 {n:'Miyarisan-BM',s:'Clostridium butyricum MIYAIRI <b>40 mg/g</b>｜<b>1 g/包</b>（妙利散散劑，衛署藥輸字第014618號）',f:'依年齡（非體重換算）',
  wm:'手冊只給「每次幾包」，<b>未載給藥頻次</b>，請依院內慣例或仿單補齊。TFDA 適應症：緩解輕度腹瀉、腹痛及便秘、整腸（調整排便）、軟便。',
  m:['3–6 歲：<b>¼ 包</b>/次（0.25 g ＝ 菌體 10 mg）',
     '6–12 歲：<b>½ 包</b>/次（0.5 g ＝ 菌體 20 mg）',
     '>12 歲：成人劑量（<b>1 包</b>/次 ＝ 1 g ＝ 菌體 40 mg）',
     '同廠另有<b>妙利散－愛錠</b>（MIYARISAN A，衛署藥輸字第011649號）為 <b>30 mg/錠</b> —— 與散劑<b>單位不同，勿互換</b>'],
  calc:null},
]},

{c:'功能性腹痛 Functional abd pain',k:'腹痛 functional abdominal pain 腸絞痛',d:[
 {n:'Buscopan',s:'hyoscine butylbromide 10 mg/糖衣錠',f:'6–12 y：10 mg TID｜12–18 y：20 mg QID',
  wm:'SmPC 為 <b>6–12 歲 10 mg TID</b> —— 年齡下限是 <b>6 歲</b>（非 5 歲），頻次是 <b>TID</b>（非 QID）。12–18 歲 20 mg QID 正確 ✅',
  m:['12–18 y：20 mg 3–4 times/day','Ref: <a href="https://www.pediatriconcall.com/drugs/hyoscine-butyl-bromide/654" target="_blank">pediatriconcall</a>'],calc:null},
 {n:'其他選項',s:'無固定體重公式',f:'TCA: Imipramine / Citalopram / Catilon / Coochil',
  m:[],calc:null},
]},

{c:'嘔吐 Antiemetics',k:'嘔吐 吐 vomiting antiemetic',d:[
 {n:'Wempty susp',s:'domperidone 1 mg/mL｜60 mL/btl',f:'(BW/4) mL',
  w:'台灣 TFDA 2014 保留兒童劑量，但<b>適應症限縮為噁心嘔吐、療程 ≤7 天</b>。禁忌：QTc 延長、心臟傳導異常、CHF、重度肝功能不全、併用 QT 延長藥或強效 CYP3A4 抑制劑。<b>歐盟 2019 已因「療效未優於安慰劑」撤銷 &lt;12 歲或 &lt;35 kg 適應症</b>。',
  m:['<b>Max</b> 750 mcg/kg/day 或 30 mg/day (= 30 cc/day)','療程 ≤7 天'],
  calc:bw=>{const x=bw/4,cap=Math.min(x,10),day=x*3;return[L('每次劑量',mL(cap),'TIDAC',x>10?'依 30 mg/day 上限封頂為 10 mL/dose':null),
   L('每日總量',mL(Math.min(day,30)),'',day>30?'計算量 '+mL(day)+' 超過 30 mL/day':null)]}},
 {n:'Emetrol',s:'domperidone 10 mg/錠',f:'(BW/40) #',
  w:'<b>錠劑無法準確分割</b>（10 kg 需 ¼ 錠），<b>兒童應一律改用 Wempty 懸液</b>。此錠劑僅適合能吞整錠的青少年。QTc 延長、心臟傳導異常、重度肝功能不全禁用。',
  m:['<b>Max</b> 30 mg/day','>12 y：1 # TID','較少 EPS，但有 ventricular arrhythmia 風險'],
  calc:bw=>{const x=bw/40,cap=Math.min(x,1);return[L('每次劑量',TB(cap),'TIDAC',x>1?'依 30 mg/day 上限封頂為 1 #/dose':null)]}},
 {n:'Prometin',rt:'口服',s:'metoclopramide 5 mg/錠｜口服劑型，同成分針劑見下一張 Imperan',f:'(BW/40) # TIDAC',
  w:'EMA 2013 的限制<b>口服與針劑一體適用</b>：<b>&lt;1 歲絕對禁用</b>；1–18 歲僅限二線；<b>0.1–0.15 mg/kg/dose、單次 ≤10 mg、日量 ≤0.5 mg/kg、療程 ≤5 天</b>。<b>與 Imperan 針劑同為 metoclopramide，勿並用。</b>公式 (BW/40) # ＝ <b>0.125 mg/kg</b>，落在 0.1–0.15 區間中段。',
  m:['<b>最小開到 ½ 錠（2.5 mg）</b> —— ¼ 錠不實用，不顯示；<b>&lt;16.7 kg 沒有任何錠數落在 0.1–0.15 mg/kg 內</b>，請改用 Imperan 針劑或 domperidone 懸液','錠數取落在 0.1–0.15 mg/kg 內、最接近 (BW/40) 的 ¼ 錠刻度（½、¾、1、1¼ …）','<b>本卡未經 TFDA 品項查證</b>（5 mg/錠取自原筆記）—— 開立前請核對院內錠劑實際含量','較易 EPS（EPS 解藥見下方 Bipiden）'],
  calc:bw=>{const lo=Math.min(0.1*bw,10),hi=Math.min(0.15*bw,10),day=Math.min(0.5*bw,30),raw=bw/40;
   /* 錠劑刻度為 ¼ 錠，但 ½ 錠（2.5 mg）以下不實用 —— 只在 ½~2 錠之間挑落在
      0.1–0.15 mg/kg 內、最接近 (BW/40) 的那一格；挑不到就是錠劑給不到 */
   let best=null;
   for(let k=2;k<=8;k++){const q=k/4,mg=q*5;
     if(mg>=lo-0.001&&mg<=hi+0.001&&(best===null||Math.abs(q-raw)<Math.abs(best-raw)))best=q;}
   const target=S('目標劑量區間',rng(MG(lo),MG(hi)),'（0.1–0.15 mg/kg；本式取 0.125 mg/kg）');
   if(best===null)return[L('每次劑量','不適用','TIDAC',
     '½ 錠 ＝ 2.5 mg，對 '+num(r1(bw))+' kg 是 '+MGKG(2.5/bw)+'，落在 0.1–0.15 之外 —— 改用 Imperan 針劑或 domperidone 懸液'),target];
   const mgv=best*5;
   return[L('每次劑量',TB(best),'TIDAC',raw>2?'已達單次上限 10 mg（2 #）':null),
    S('實際給予',MG(mgv),'（5 mg/錠；＝ '+MGKG(mgv/bw)+'）'),
    target,
    L('每日上限',MG(day),'≤0.5 mg/kg/day，療程 ≤5 天',null),
    S('每日上限錠數',num(r2(day/5))+' #','（5 mg/錠）')]}},
 {n:'Imperan (metoclopramide inj)',rt:'針劑',s:'metoclopramide 10 mg/2 mL/amp（5 mg/mL）｜舊品項 Pulin／Primperan 腹寧朗 同成分',f:'(BW×0.1~0.15) mg ÷ 10 ＝ amp 數',
  w:'EMA 2013：<b>&lt;1 歲絕對禁用</b>；1–18 歲僅限二線。劑量為 <b>0.1–0.15 mg/kg</b>（0.2 mg/kg 是台灣仿單絕對極量，不作常規）；<b>單次 ≤10 mg（＝1 amp）、日量 ≤0.5 mg/kg、療程 ≤5 天</b>；IV 需緩注 ≥3 分鐘。<b>Pulin、Primperan（腹寧朗）與本品同為 metoclopramide，勿並用。</b>',
  m:['<b>1 amp ＝ 10 mg/2 mL ＝ 5 mg/mL</b>','<b>未滿 1 amp 不要四捨五入到整支</b> —— 依「實際抽取量」的 mL 數抽藥','能口服時改用上一張 Prometin 錠（同成分，勿並用）','較易 EPS（EPS 解藥見下方 Bipiden）'],
  calc:bw=>{const lo=Math.min(0.1*bw,10),hi=Math.min(0.15*bw,10),day=Math.min(0.5*bw,30);
   return[L('注射劑量',rng(MG(lo),MG(hi)),'IM / IV（緩注 ≥3 分鐘）',0.15*bw>10?'已達單次上限 10 mg':null),
    L('開立支數',rng(num(r2(lo/10)),num(r2(hi/10)))+' amp','（1 amp ＝ 10 mg/2 mL）',null),
    S('實際抽取量',rng(mL2(lo/5),mL2(hi/5)),'（5 mg/mL；amp 數 ×2 mL）'),
    L('每日上限',MG(day),'≤0.5 mg/kg/day，療程 ≤5 天',null),
    S('每日上限支數',num(r2(day/10))+' amp','（1 amp ＝ 10 mg）')]}},
 {n:'Bipiden',rt:'針劑',s:'biperiden 5 mg/mL/amp｜EPS 解藥',f:'(BW×0.04) mg IM 或 1~2 mg slow IV',
  m:['Q30min，<b>Max</b> 4 次'],
  calc:bw=>[L('IM 劑量',MG(0.04*bw),'Q30min, ≤4 次',null)]},
 {n:'Zofran',rt:'錠／針',s:'ondansetron 8 mg/錠；8 mg/4 mL/amp｜5HT3 inhibitor',f:'(BW×0.15) mg IV，Max 8 mg',
  wm:'<b>Max 8 mg/dose</b>（53 kg 即封頂）。急性腸胃炎給 <b>4 mg 即足</b>。32 mg 單次劑量因 QT 延長已全球禁用。',
  m:['<b>Max</b> 8 mg/dose','急性腸胃炎 4 mg 即足','$自費 250 元'],
  calc:bw=>{const raw=0.15*bw,mgv=Math.min(raw,8);return[L('劑量',MG(mgv),'IV',raw>8?'已達單次上限 8 mg（算出 '+MG(raw)+'）':null),
   L('抽取量',mL(mgv/2),'（8 mg/4 mL = 2 mg/mL）',null)]}},
 {n:'Mosapride',s:'mosapride citrate｜台灣無兒童適應症（off-label）',f:'0.3 mg/kg/day 分 2 次',
  w:'<b>兒科用量為 0.3 mg/kg/day 分 2 次 —— 注意不是 3 mg/kg/day，兩者差 10 倍。</b>台灣仿單成人量 5 mg TID = <b>15 mg/day</b>（60 kg 成人約 0.25 mg/kg/day）；若誤用 3 mg/kg/day，20 kg 兒童會算出 60 mg/day，是<b>成人每日最大量的 4 倍</b>。',
  m:['台灣無兒童適應症，屬 off-label 使用','成人：5 mg TID（15 mg/day）'],
  r:[['Komura 2017 (PMID 27561215)','https://pubmed.ncbi.nlm.nih.gov/27561215/'],['pediatriconcall','https://www.pediatriconcall.com/drugs/mosapride/784']],
  calc:bw=>{const day=Math.min(0.3*bw,15);return[L('每日總量',MG(day),'分 2 次',0.3*bw>15?'已達成人每日量 15 mg':null),
   L('每次劑量',MG(day/2),'BID',null)]}},
]},

{c:'上腹痛 Epigastralgia',k:'上腹痛 胃痛 制酸 PPI GERD 胃食道逆流',d:[
 {n:'Strocain',s:'oxethazaine 5 mg/錠｜含局部麻醉藥的制酸劑',f:'限能整顆吞錠者，1 # TID~QID',
  w:'<b>仿單為「應整顆服用，不可咬碎或咀嚼」—— 不可剝半。</b>剝半會讓局部麻醉劑接觸口咽 → 麻木、幼童嗆咳。台灣仿單<b>無兒童劑量</b>，且止痛作用會<b>掩蓋腹痛症狀</b>不利診斷。建議<b>限用於能整顆吞錠的青少年</b>，不要用體重換算。',
  m:['<b>整顆吞服</b>，不可剝半、咬碎、磨粉','若未做胃鏡確認符合健保規範，需自費'],
  calc:bw=>[L('建議用法','1 #','TID ~ QID（限能吞整錠者）',null)]},
 {n:'Biotase 妙化錠',s:'lipase + newlase + diastase 複方消化酵素',f:'1 # TID PC（依年齡調整）',
  wm:'消化酵素複方，用於消化不良、腹脹。<b>與胰臟外分泌功能不全（如囊性纖維化）所需的胰酵素製劑不同</b>，劑量與適應症不可互換 —— 後者須依脂肪酶單位與脂肪攝取量計算。本品為症狀性用藥，<b>療效證據有限</b>，非必要用藥。飯後服用。',
  m:['1 # TID PC','幼童可依年齡減半','非胰臟功能不全之替代療法'],calc:null},
 {n:'Tido',s:'Al(OH)₃ + Mg(OH)₂ + simethicone｜<b>各成分含量依院內品項</b>',f:'依年齡',
  m:['<b>≥12 y / 成人</b>：2–4 # TID–QID，Max 16 #/day','<b>6–11 y</b>：1 # TID','<b>3–5 y</b>：0.5 # TID'],calc:null},
 {n:'Sucralfate (Scrat susp.)',s:'sucralfate 1 g/pk',f:'40–80 mg/kg/day 分 Q6H，單次 Max 1 g',
  w:'<b>小體重須依體重換算，不可直接套固定包數。</b>0.5 pk QID 用在 10 kg 幼兒 = <b>200 mg/kg/day</b>，是建議量 40–80 mg/kg/day 的 <b>2.5–5 倍</b>。固定 0.5–1 g QID 本身是 Micromedex 收錄的 off-label 用法，但要落在 40–80 mg/kg/day 區間內約需 <b>25 kg 以上</b>，小小孩不適用。',
  m:['40–80 mg/kg/day 分 4 次（Q6H）','單次 <b>Max</b> 1 g（1 pk）；每日 <b>Max</b> 4 g','Micromedex 兒科：壓力性潰瘍預防 40–80 mg/kg/day 分 4 次'],
  calc:bw=>{const lo=Math.min(40*bw/4,1000),hi=Math.min(80*bw/4,1000);
   return[L('每次劑量',rng(MG(lo),MG(hi)),'QID (Q6H)',80*bw/4>1000?'高端已達單次上限 1 g':null),
    L('換算 pk（1 g/pk）',rng(num(r2(lo/1000)),num(r2(hi/1000)))+' pk','QID',null),
    L('每日總量',rng(MG(lo*4),MG(hi*4)),'40–80 mg/kg/day',null)]}},
 {n:'Famotidine 20 mg / Kimodin susp',s:'famotidine 20 mg/錠；Kimodin 8 mg/mL｜H2 blocker',f:'0.5 mg/kg BID',
  m:['<b>Max</b> 40 mg BID 或 2 mg/kg/day'],
  calc:bw=>{const mgv=Math.min(0.5*bw,40);return[L('每次劑量',MG(mgv),'BID',0.5*bw>40?'已達上限 40 mg':null),
   L('Kimodin 8 mg/mL',mL(mgv/8),'BID',null)]}},
 {n:'Famodine IV',rt:'針劑',s:'famotidine 10 mg/mL 注射液',f:'>1 y：0.25–0.5 mg/kg Q12H',
  m:['成人 20 mg IV Q12H','<b>Max</b> 40 mg/day'],
  calc:bw=>[L('每次劑量',rng(MG(0.25*bw),MG(0.5*bw)),'IV Q12H',bw*0.5*2>40?'每日超過 40 mg 上限':null)]},
 {n:'Nexium 40 mg',s:'esomeprazole 40 mg/腸溶顆粒膠囊｜PPI',f:'1–11 y 依體重固定劑量（非 mg/kg）',
  w:'<b>依體重固定劑量，不用 mg/kg 換算。</b>仿單為 <b>1–11 歲：&lt;20 kg → 10 mg QD；≥20 kg → 10–20 mg QD</b>（症狀性 GERD 一律 10 mg）；FDA 明載「<b>超過 1 mg/kg/day 未經研究</b>」，用 1 mg/kg 在大孩子會超過仿單上限 20 mg（35 kg 算出 35 mg）。另：40 mg 為<b>腸溶顆粒膠囊，不可剝半</b>（會破壞腸溶衣與劑量準確性）。',
  m:['1–11 y：<20 kg → 10 mg QD；≥20 kg → 10–20 mg QD','症狀性 GERD 一律 10 mg QD','<b>不可剝半、磨粉</b>'],
  r:[['DailyMed NEXIUM 標示','https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f4853677-1622-4037-688b-fdf533a11d96']],
  calc:bw=>[L('1–11 歲建議',bw<20?'10 mg QD':'10 ~ 20 mg QD','（症狀性 GERD 用 10 mg）',null)]},
 {n:'Takepron 30 mg',s:'lansoprazole 30 mg/腸溶微粒崩散錠（另有 OD 15 mg）｜PPI',f:'≤30 kg 用 OD 15 mg｜>30 kg 用 30 mg',
  wm:'mg/kg 值本身合理（文獻 0.7–1.5），但<b>劑型無法對應</b>：<b>≤30 kg 應改用 Takepron OD 15 mg</b>，30 mg 為腸溶微粒崩散錠<b>不可磨粉、不可剝半</b>。FDA 另註「1 個月–&lt;1 歲症狀性 GERD 無效」。',
  m:['≤30 kg：15 mg QD（OD 劑型）','>30 kg：30 mg QD','<b>不可磨粉、剝半</b>'],
  calc:bw=>[L('建議劑量',bw<=30?'15 mg QD（OD 劑型）':'30 mg QD','',null),
   S('參考 mg/kg',rng(MG(bw),MG(1.2*bw)),'（1–1.2 mg/kg，僅供對照）')]},
 {n:'Lansoprazole 30 mg cap',s:'lansoprazole 30 mg/膠囊｜PPI',f:'見說明',
  wm:'「&gt;12 y 15 mg QD」<b>僅適用非糜爛性 GERD</b>。已<b>確診糜爛性食道炎應為 30 mg QD × 8 週</b>。',
  m:['<b>1–11 y</b>：<30 kg → 15 mg QD；>30 kg → 30 mg QD','<b>>12 y 非糜爛性 GERD</b>：15 mg QD','<b>>12 y 糜爛性食道炎</b>：30 mg QD × 8 週'],
  calc:bw=>[L('1–11 y 建議',bw<30?'15 mg QD':'30 mg QD','',null)]},
 {n:'Pantoprazole (Pantoloc inj)',rt:'針劑',s:'pantoprazole 40 mg/vial｜IV｜PPI',f:'依<b>體重</b>分檔（非年齡）',
  w:'分檔依據為<b>純體重</b>，不可混用年齡（否則會<b>誤判 11 歲 45 kg 與 13 歲 35 kg</b> 這類個案）：<b>&gt;15–≤40 kg → 20 mg QD；&gt;40 kg → 40 mg QD</b>。另注意 <b>7 天療程上限</b>與 <b>15 分鐘輸注</b>。',
  m:['>15–≤40 kg：20 mg QD','>40 kg：40 mg QD','療程上限 7 天｜輸注時間 15 分鐘'],
  calc:bw=>[L('建議',bw<=40?'20 mg QD':'40 mg QD','IV 輸注 15 分鐘，療程 ≤7 天',bw<=15?'≤15 kg 無建議劑量，資料不足':null)]},
 {n:'Algitab',s:'alginic acid 200 + Al(OH)₃ 30 + MgCO₃ 40 mg/咀嚼錠',f:'不建議兒童慢性 GERD 使用',
  m:['低品質研究，療效證據不足（<a href="https://www.uptodate.com/contents/management-of-gastroesophageal-reflux-disease-in-children-and-adolescents" target="_blank">UpToDate</a>）'],calc:null},
]},

{c:'抗生素 Antibiotics',k:'抗生素 antibiotic 中耳炎 AOM 鼻竇炎 肺炎 咽炎 UTI 蜂窩性組織炎 doxycycline 多喜黴素 恙蟲病 四環黴素 立克次體 萊姆病',d:[
 {n:'Curam 水劑',rt:'口服',s:'amoxicillin/clavulanate 50/12.5 mg/mL（<b>4:1</b>）懸液｜劑量以 amoxicillin 計｜北醫另有針劑（5:1、以總重計），見下一張',f:'(0.3×BW) mL',
  w:'<b>此 45 mg/kg/day 不適用於 AOM。</b>AOM 需 amoxicillin <b>80–90 mg/kg/day 分 BID</b>（台灣 PNSP 盛行率高）—— 請用下方 ★ 併用方案。45 mg/kg/day 只適用於<b>無風險因子的低抗藥區鼻竇炎、GAS 咽炎、皮膚軟組織感染</b>。另注意 Curam 4:1 在 45 mg/kg/day 時 clavulanate 已達 11.25 mg/kg/day，高於 Stanford 建議的 &lt;10。<br><b>約 33 kg 起，依體重換算的 clavulanate 會超過成人每日量（約 375 mg）</b> —— 水劑本來就是給小小孩的，大孩子請直接用 <b>Curam 錠 875/125 BID</b>，不要再依體重放大。這也是為什麼高劑量 AOM 要用下方的 ★ 併用方案：把 clavulanate 鎖在 45 mg/kg/day 的水位，缺的 amoxicillin 由 Amolin 補。',
  m:['= 45 mg/kg/day','High dose amoxicillin = 80–90 mg/kg/day','若院內有 7:1 (400/57) 或 14:1 ES-600 應優先使用',
     '院內另有 <b>Curam F.C. 1 g 膜衣錠</b>（諾快寧，衛署藥輸字第024808號；amoxicillin 875 ／ clavulanic acid 125 ＝ <b>7:1</b>）—— 大孩子水劑體積過大時改用錠劑，且 7:1 的 clavulanate 負擔低於水劑的 4:1。錠劑只能整錠／剖半，<b>體重太小給不了</b>，換算見 <a href="/prototype-amox-cap.html" style="color:var(--accent);font-weight:700">錠劑／替代劑型換算 →</a>（<b>試驗品，未經藥師核對</b>）'],
  r:[['AAP 2013 AOM 指引','https://publications.aap.org/pediatrics/article/131/3/e964/30912/The-Diagnosis-and-Management-of-Acute-Otitis-Media'],['Stanford Augmentin Guide','https://www.stanfordchildrens.org/content-public/pdf/antimicrobial-stewardship-program/augmentin-dosing-guide.pdf']],
  calc:bw=>[L('每次劑量',mL(0.3*bw),'TID',null),L('每日總量',MG(45*bw)+' amox','45 mg/kg/day',null),
   S('Clavulanate 日量',MG(11.25*bw),'（11.25 mg/kg/day）',
     11.25*bw>375
       ?'已超過成人每日 clavulanate 量（約 375 mg）—— 約 33 kg 起即發生。請改用 Curam 錠 875/125 BID，勿再依體重放大水劑'
       :'高於 Stanford 建議上限 10 mg/kg/day（4:1 配方固有限制）')]},
 {n:'Curam IV',rt:'針劑',s:'amoxicillin/clavulanate 500/100 與 1000/200 mg/vial（<b>5:1</b>）｜開立單位為 mg <b>總重</b>',f:'36 mg/kg/dose（總重，非 amoxicillin）',
  w:'<b>開立的 mg 數是「總重」＝ amoxicillin ＋ clavulanate，不是 amoxicillin。</b>北醫習慣以總重開立（一支 1200 mg ＝ amox 1000 ＋ clav 200）。下方「每次劑量」即為開立用的數字。<br><b>與 Curam 水劑同名，劑型務必確認。</b>水劑為 (0.3×BW) mL TID ＝ 45 mg/kg/day 且比例為 <b>4:1</b>；針劑為 36 mg/kg/dose 且比例為 <b>5:1</b> —— 換算基準與配方比例都不同，混用會嚴重偏離。<br>中度 Q8H、重度 Q6H。<br><b>單次 Max 1200 mg 就是成人單次劑量</b>，<b>約 33 kg（1200÷36）即達到</b>。超過此體重維持 1200 mg 不再往上加 —— 這是正確收斂到成人劑量，不是給不足，<b>不要為了湊 mg/kg 而開超過一支</b>。Q8H×1200 ＝ 3.6 g/day、Q6H×1200 ＝ 4.8 g/day，分別對應成人常規與重症上限。',
  m:['中度：36 mg/kg/dose Q8H｜重度 Q6H','單次 <b>Max</b> 1200 mg（＝成人量，約 33 kg 達到）','每日 Max 3.6 g（Q8H）／4.8 g（Q6H）','5:1 配方：總重 ÷ 6 × 5 = amoxicillin'],
  calc:bw=>{const d=Math.min(36*bw,1200),amox=d*5/6,clav=d/6;
   return[L('每次劑量（總重．開立用）',MG(d),'Q8H（中度）／Q6H（重度）',36*bw>1200?'已達成人單次量 1200 mg（依體重算出 '+MG(36*bw)+'）—— 維持 1200，勿再往上':null),
    S('其中 amoxicillin',MG(amox),'（'+num(r1(amox/bw))+' mg/kg/dose）'),
    S('其中 clavulanate',MG(clav),'（'+num(r1(clav/bw))+' mg/kg/dose）'),
    S('換算 vial',num(r2(d/1200))+' 支','（1000/200 規格，1200 mg/支）'),
    L('Q8H 每日總重',MG(d*3),'中度',null),
    S('　　clavulanate 累積',MG(clav*3),'/day'),
    L('Q6H 每日總重',MG(d*4),'重度',null),
    S('　　clavulanate 累積',MG(clav*4),'/day')]}},
 {n:'Amolin',rt:'口服',s:'amoxicillin 25 mg/mL',f:'(0.6×BW) mL',
  wm:'45 mg/kg/day 適用於 GAS 咽炎與低風險鼻竇炎。<b>AOM 需 80–90 mg/kg/day</b>，請用下方 ★ 併用方案。',
  m:['= 45 mg/kg/day','AOM 高劑量請見下方併用方案',
     '<b>沒有水劑時：amoxicillin 250 mg 膠囊泡水至 10 mL ＝ 25 mg/mL，與水劑同濃度，故 (0.6×BW) 的公式不變</b>，只多一個「先泡」的步驟（膠囊交家長回家泡，藥局不做分包）。詳見 <a href="/prototype-amox-cap.html" style="color:var(--accent);font-weight:700">錠劑／替代劑型換算 →</a>（<b>試驗品，未經藥師核對</b>）'],
  calc:bw=>[L('每次劑量',mL(0.6*bw),'TID',null),L('每日總量',MG(45*bw),'45 mg/kg/day',null)]},
 {n:'★ AOM 高劑量：Curam + Amolin 併用',rt:'口服',s:'目標 amoxicillin 90 mg/kg/day｜clavulanate 維持不變｜<b>用水劑，非針劑</b>',
  f:'Curam 45 + Amolin 45 mg/kg/day',
  m:['Curam 為 <b>4:1</b> 配方，單靠它拉到 90 mg/kg/day 會讓 clavulanate 達 22.5 mg/kg/day（必然嚴重腹瀉）',
     '故 Curam 只給到 45 mg/kg/day，<b>不足的 45 由純 amoxicillin (Amolin) 補足</b>，clavulanate 總量不變',
     'Stanford 抗生素管理：clavulanate 建議 <b>&lt;10 mg/kg/day</b>',
     '<b>適用</b>：AOM 全年齡；ABS 有風險因子者（&lt;2 歲、托嬰/托兒所、近 1 個月用過抗生素、近期住院、免疫低下、症狀嚴重）',
     '<b>上限</b>：amoxicillin 4 g/day（≈44 kg 即封頂）',
     '體重 &gt;30 kg 糖漿體積過大，建議改 Curam 錠 + Amoxicillin 250/500 mg 膠囊',
     '<b>任一端沒有水劑時，公式都不必改</b>：Amolin 端可用 amoxicillin 250 mg 膠囊泡水至 10 mL（＝ 25 mg/mL，同濃度）；Curam 端可用 F.C. 1 g 膜衣錠（7:1，但只能整錠／剖半，體重太小給不了）。詳見 <a href="/prototype-amox-cap.html" style="color:var(--accent);font-weight:700">錠劑／替代劑型換算 →</a>（<b>試驗品，未經藥師核對</b>）',
     'Ref: <a href="https://publications.aap.org/pediatrics/article/131/3/e964/30912/The-Diagnosis-and-Management-of-Acute-Otitis-Media" target="_blank">AAP 2013 AOM</a> ｜ <a href="https://www.stanfordchildrens.org/content-public/pdf/antimicrobial-stewardship-program/augmentin-dosing-guide.pdf" target="_blank">Stanford Augmentin Guide</a>'],
  calc:bw=>{
    const want=90*bw, daily=Math.min(want,4000), capped=want>4000;
    const cDaily=daily/2, aDaily=daily/2;
    const cmL=cDaily/50, amL=aDaily/25;
    const clav=cmL*12.5, clavKg=clav/bw;
    const combo=(n)=>'Curam <b>'+mL(cmL/n)+'</b> ＋ Amolin <b>'+mL(amL/n)+'</b>';
    return[
      L('BID 用法（AAP 高劑量標準）',combo(2),'兩瓶各取此量，同時給，一日 2 次',null),
      L('TID 用法（台灣 Curam 仿單）',combo(3),'兩瓶各取此量，同時給，一日 3 次',null),
      L('Amoxicillin 每日總量',MG(daily),num(r1(daily/bw))+' mg/kg/day',capped?'已達 4 g/day 上限，實際降為 '+num(r1(daily/bw))+' mg/kg/day':null),
      S('Clavulanate 每日總量',MG(clav),'（'+num(r2(clavKg))+' mg/kg/day）',clavKg>10?'超過建議上限 10 mg/kg/day（Curam 4:1 配方之固有限制）':null)
    ];}},
 {n:'Zithromax susp',s:'azithromycin 40 mg/mL｜15 mL/btl',f:'依適應症分流（見下）',
  w:'<b>常規 10 mg/kg/day QD</b>（AOM／鼻竇炎，療程 3 天）為主要用法。<b>兩個例外需另外記</b>：<b>GAS 咽炎 12 mg/kg × 5 天</b>（Max 500 mg/day）、<b>CAP 10 mg/kg 第 1 天 → 5 mg/kg 第 2–5 天</b>。台灣兒童 macrolide-resistant <i>M. pneumoniae</i> 2019 年 62.5%、2020 年 85.7% —— 應保留給黴漿菌、百日咳、非典型病原或真正 β-lactam 過敏者。',
  m:['AOM / 鼻竇炎：10 mg/kg QD × 3 天','GAS 咽炎：12 mg/kg QD × 5 天（Max 500 mg/day）','CAP：10 mg/kg D1 → 5 mg/kg D2–5'],
  calc:bw=>[L('AOM / 鼻竇炎',mL(Math.min(10*bw,500)/40),'QD × 3 天',null),
   L('GAS 咽炎',mL(Math.min(12*bw,500)/40),'QD × 5 天',12*bw>500?'已達 500 mg/day 上限':null),
   L('CAP 第 1 天',mL(Math.min(10*bw,500)/40),'QD',null),
   L('CAP 第 2–5 天',mL(Math.min(5*bw,250)/40),'QD',null)]},
 {n:'Zithromax 250 mg',s:'azithromycin 250 mg/錠｜體重 >20 kg 可開',f:'(BW/25) #',
  wm:'同懸液，<b>療程需依適應症分流</b>：AOM/鼻竇炎 3 天、GAS 咽炎 5 天（12 mg/kg）、CAP 5 天遞減。',
  m:['<b>Max</b> 2 # QD'],
  calc:bw=>{const x=bw/25;return[L('每次劑量',TB(Math.min(x,2)),'QD',x>2?'已達上限 2 #':null)]}},
 {n:'Klaricid',s:'clarithromycin 25 mg/mL',f:'(BW×0.3) mL = 7.5 mg/kg Q12H',
  wm:'「Max 500 mg/dose」是<b>成人 / MAC / H. pylori</b> 的上限；<b>GAS 咽炎兒童為 250 mg/dose BID</b>。FDA 療程為 <b>10 天</b>。macrolide 抗藥性提醒同 azithromycin。',
  m:['療程 10 天（FDA）','<b>Max</b> 500 mg/dose（一般感染）；GAS 咽炎 250 mg/dose'],
  calc:bw=>{const mgv=7.5*bw,cap=Math.min(mgv,500);return[L('每次劑量',mL(cap/25),'Q12H',mgv>500?'已達上限 500 mg':null),
   S('= mg',MG(cap),''),
   L('GAS 咽炎上限',MG(Math.min(mgv,250)),'Q12H',mgv>250?'GAS 咽炎應封頂於 250 mg/dose':null)]}},
 {n:'Ulexin',s:'cephalexin 25 mg/mL｜GAS・UTI・cellulitis',f:'(BW/2) mL = 50 mg/kg/day',
  wm:'<b>依適應症分流</b>：<b>GAS 咽炎</b> CDC 建議 20 mg/kg/dose <b>BID × 10 天</b>即可，不必 q6h；<b>中耳炎</b>則需 75–100 mg/kg/day。<b>發燒性 UTI / 腎盂腎炎</b>因台灣第一代 cephalosporin 抗藥率高，建議依院內 antibiogram 改 2/3 代（下泌尿道感染可用）。',
  m:['第一代 cephalosporin 25–50 mg/kg/day q6–8H'],
  calc:bw=>{const gen=Math.min(50*bw,4000),oLo=Math.min(75*bw,4000),oHi=Math.min(100*bw,4000);
   return[L('一般用法（50 mg/kg/day）',mL(gen/4/25),'Q6H',50*bw>4000?'已達成人每日上限 4 g':null),
    L('GAS 咽炎',mL(Math.min(20*bw,500)/25),'BID × 10 天',null),
    L('中耳炎（75–100 mg/kg/day）',oLo>=oHi?mL(4000/4/25):rng(mL(oLo/4/25),mL(oHi/4/25)),'Q6H',
      100*bw>4000?'已達成人每日上限 4 g（依體重算出 '+MG(100*bw)+'/day）':null)]}},
 {n:'Cephalexin 250 mg',s:'cephalexin 250 mg/膠囊｜體重 >20 kg',f:'(BW/20) #',
  wm:'同 Ulexin，<b>依適應症分流</b>：GAS 咽炎 20 mg/kg/dose BID × 10 天；中耳炎 75–100 mg/kg/day。',
  m:['<b>Max</b> 2 # Q6H'],
  calc:bw=>{const x=bw/20;return[L('每次劑量',TB(Math.min(x,2)),'Q6H',x>2?'已達上限 2 #':null)]}},
 {n:'Sulfacotrim',s:'TMP 8 + SMX 40 mg/mL 懸液｜以 trimethoprim 計',f:'(BW/2) mL',
  wm:'濃度為 <b>TMP 8 + SMX 40 mg/mL</b>（不是 25 mg/mL）。依此換算，(BW/2) mL q12h = <b>TMP 8 mg/kg/day ✅</b>。但<b>台灣社區 E. coli 對 TMP-SMX 抗藥率 &gt;40–50%，不宜作發燒性 UTI 經驗用藥</b>；且對 GAS 涵蓋不可靠，單純非化膿性蜂窩性組織炎不應單用（懷疑 CA-MRSA 膿瘍才是好選擇）。',
  m:['= TMP 8 mg/kg/day 分 2 次','蠶豆症建議勿用'],
  calc:bw=>[L('每次劑量',mL(bw/2),'Q12H',null),S('= TMP',MG(4*bw),'（每次，8 mg/kg/day）')]},
 {n:'Baktar',s:'TMP 80 + SMX 400 mg/錠',f:'(BW/20) #',
  wm:'抗藥性提醒同 Sulfacotrim：<b>不宜作發燒性 UTI 經驗用藥</b>，對 GAS 涵蓋不可靠。',
  m:['<b>Max</b> 2 # Q12H','蠶豆症建議勿用'],
  calc:bw=>{const x=bw/20;return[L('每次劑量',TB(Math.min(x,2)),'Q12H',x>2?'已達上限 2 #':null)]}},
  {n:'Doxymycin (doxycycline) 100 mg 腸溶膠囊',rt:'口服',
   s:'doxycycline hyclate 100 mg/cap｜院內碼 ME01M1・健保 AC35692100｜藍/黃雙色(DEC)｜永信',
   f:'<45 kg: 2.2~4.4 mg/kg/day 分 BID ｜ ≥45 kg: 100 mg BID',
   wm:'<b>💊 院內規格與外觀：</b>Doxymycin Cap 100mg（多喜黴素腸溶膠囊，永信），外觀為<b>藍／黃雙色膠囊，標記 DEC</b>（院內碼：<code>ME01M1</code>、健保碼：<code>AC35692100</code>）。<br><b>⚠️ 重要劑型注意事項：</b>本品為<b>腸溶膠囊，請整顆吞服，不可咬碎或磨粉！</b>需配<b>充足水分（一杯水）並維持坐姿／立姿</b>吞服，服藥後 30 分鐘內勿立即平躺以防食道炎／潰瘍。<br><b>⚠️ 交互作用與防護：</b>請與<b>牛奶、乳製品、制酸劑、鐵劑、鈣片間隔 2 小時以上</b>服用；服藥期間注意防曬遮蔽（光敏感性）。懷孕分級 <b>D</b>，孕婦及授乳婦避免使用。<br><b>💡 破除兒童牙齒染色迷思（美國 CDC & AAP 實證）：</b>早期四環黴素因與鈣螯合導致牙齒變色，但 <b>doxycycline 與鈣結合力極低</b>。美國 CDC 及 AAP 指引證實：<b>8 歲以下兒童短療程（≤21 天）使用，並不會造成牙齒永久染色或琺瑯質發育不全！</b><br><b>⚠️ 恙蟲病與立克次體重症一線救命用藥：</b>對恙蟲病（Scrub typhus）、洛磯山斑點熱（RMSF）等立克次體重症感染，<b>不限年齡皆為首選第一線救命抗生素</b>（切勿因恐懼牙齒染色而延誤治療造成生命危險）。',
   m:['<b>&lt;45 kg</b>：2.2–4.4 mg/kg/day，分 Q12H（BID）',
      '<b>≥45 kg 或成人</b>：100–200 mg/day，常規 100 mg Q12H（BID，每次 1 顆）',
      '恙蟲病/立克次體重症：4.4 mg/kg/day 分 BID',
      '單次 <b>Max</b> 100 mg；每日 Max 200 mg',
      '腸溶膠囊：整顆吞服，不可磨粉咀嚼'],
   r:[['Doxymycin 100mg 仿單 PDF','https://www.cth.org.tw/public/medi_news/ed8f712a81fc5dc7837ed14e3eed975f.pdf'],['NEJS: 兒童可以使用四環黴素治療感染嗎','https://www.nejs.app/2019/10/blog-post.html'],['CDC: Doxycycline and Tooth Staining','https://www.cdc.gov/rmsf/healthcare-providers/treatment.html'],['AAP Pediatrics: No Tooth Staining with Doxycycline','https://publications.aap.org/pediatrics/article/135/5/e1124/33946/No-Tooth-Staining-for-Children-Treated-with']],
   calc:bw=>{
     if(bw>=45){
       return[
         L('常規劑量（≥45 kg）',TB(1)+'（100 mg）','Q12H（BID）','已達常規/成人標準量 100 mg BID'),
         L('每日總量',MG(200),'分 2 次',null)
       ];
     }
     const loD=Math.min(1.1*bw,100), hiD=Math.min(2.2*bw,100);
     const loTot=Math.min(2.2*bw,200), hiTot=Math.min(4.4*bw,200);
     return[
       L('每次劑量（Q12H）',rng(MG(loD),MG(hiD)),'Q12H（分 2 次）',hiD>=100?'已達單次上限 100 mg':null),
       S('　一般感染（2.2 mg/kg/day）',MG(loD)+' / 次','（'+TB(loD/100)+'）'),
       S('　重症/恙蟲病（4.4 mg/kg/day）',MG(hiD)+' / 次','（'+TB(hiD/100)+'）'),
       L('每日總量',rng(MG(loTot),MG(hiTot)),'2.2 ~ 4.4 mg/kg/day（Max 200 mg）',4.4*bw>200?'已達每日上限 200 mg':null)
     ];
   }},
 {n:'抗生素藥膏',rt:'外用',s:'tetracycline 眼膏／fusidic acid 2% cream｜外用',f:'Tetracycline 1 PRN｜Fucidin Cream 1 TID',
  m:['Tetracycline：眼藥或一般外傷','Fucidin：懷疑 CA-MRSA'],calc:null},
 {n:'Ampicillin IV',rt:'針劑',s:'ampicillin｜<b>vial 規格依院內</b>（常見 250 / 500 / 1000 mg）',f:'100 mg/kg/day Q6H（中度）｜100–200 mg/kg/day（重度）',
  wm:'與手冊一致 ✅。<b>腦膜炎 300 mg/kg/day</b>（國際多寫 300–400 mg/kg/day 分 Q6H，手冊取下限）。單日上限一般 12 g。GBS、Listeria、腸球菌之首選。',
  m:['中度 100 mg/kg/day Q6H','重度 100–200 mg/kg/day','腦膜炎 300 mg/kg/day'],
  calc:bw=>[L('中度（每日）',MG(Math.min(100*bw,12000)),'分 Q6H = '+MG(Math.min(25*bw,3000))+'/次',100*bw>12000?'已達成人每日上限 12 g':null),
   L('重度（每日）',rng(MG(100*bw),MG(200*bw)),'分 Q6H',null),
   L('腦膜炎（每日）',MG(Math.min(300*bw,12000)),'分 Q6H',300*bw>12000?'已達每日 12 g 上限':null)]},
 {n:'Oxacillin IV',rt:'針劑',s:'oxacillin｜抗葡萄球菌青黴素（MSSA）｜<b>vial 規格依院內</b>',f:'100 mg/kg/day Q6H（中度）｜100–200 mg/kg/day（重度）',
  wm:'與手冊一致 ✅。單次 <b>Max 2000 mg Q4H</b>。<b>只涵蓋 MSSA，對 MRSA 無效</b> —— 懷疑 CA-MRSA 請改 vancomycin。注意肝毒性與間質性腎炎。',
  m:['單次 <b>Max</b> 2 g；每日 Max 12 g','口服劑型 50–100 mg/kg/day'],
  calc:bw=>[L('中度（每日）',MG(100*bw),'分 Q6H = '+MG(Math.min(25*bw,2000))+'/次',25*bw>2000?'單次已達 2 g 上限':null),
   L('重度（每日）',rng(MG(100*bw),MG(Math.min(200*bw,12000))),'分 Q6H',null)]},
 {n:'Cefazolin IV',rt:'針劑',s:'cefazolin｜第一代 cephalosporin｜<b>vial 規格依院內</b>',f:'100 mg/kg/day Q6–8H（中度）｜100–150 mg/kg/day（重度）',
  wm:'與手冊一致 ✅。心導管等手術預防為 <b>首劑於術前 30 分鐘</b>給予。單次一般 Max 1 g（重症可至 2 g），每日 Max 6 g。<b>不進中樞神經</b>，腦膜炎不可用。',
  m:['手術預防：術前 30 分鐘首劑','單次 Max 1 g（重症 2 g）'],
  calc:bw=>{const mod=Math.min(100*bw,6000),sLo=Math.min(100*bw,6000),sHi=Math.min(150*bw,6000);
   return[L('中度（每日）',MG(mod),'分 Q6–8H',100*bw>6000?'已達成人每日上限 6 g':null),
    L('每次（Q6H）',MG(Math.min(25*bw,1000)),'',25*bw>1000?'已達單次 1 g':null),
    L('重度（每日）',sLo>=sHi?MG(6000):rng(MG(sLo),MG(sHi)),'',150*bw>6000?'已達成人每日上限 6 g':null)]}},
 {n:'Gentamicin IV',rt:'針劑',s:'gentamicin 80 mg/vial｜aminoglycoside',f:'5–7 mg/kg/day QD（建議）｜2.5 mg/kg/dose Q8H（舊法）',
  wm:'手冊兩種給法並列，<b>現行建議為每日單次給藥（5–7 mg/kg QD）</b> —— 濃度依賴型殺菌、腎毒性較低，優於 Q8H 分次。<br><b>「單一劑量勿超過 80 mg（1 vial）」須向科內確認語意</b>：若為一瓶容量的提醒，大孩子照 5–7 mg/kg 本來就會超過一瓶（40 kg 需 200–280 mg），應抽多瓶；若為院內硬性上限，則大孩子會治療不足。<b>下方顯示的是體重換算的實際應給量</b>，並在超過一瓶時提示瓶數。<br><b>療程勿超過 7 天</b>；須監測腎毒性與耳毒性（不可逆聽損）並驗 peak/trough。',
  m:['優先每日單次給藥 5–7 mg/kg','80 mg 之語意待科內確認（瓶量 vs 上限）','療程 ≤7 天；監測腎功能與聽力'],
  calc:bw=>{const lo=5*bw,hi=7*bw;
   return[L('每日單次',rng(MG(lo),MG(hi)),'QD',hi>80?'超過一瓶（80 mg），需抽 '+num(r1(Math.ceil(hi/80)))+' 瓶':null),
    L('舊法每次（Q8H）',MG(2.5*bw),'Q8H',null)]}},
 {n:'Claforan (cefotaxime) IV',rt:'針劑',s:'cefotaxime｜第三代 cephalosporin｜<b>vial 規格依院內</b>',f:'100 mg/kg/day Q6H（中度）｜100–150 mg/kg/day（重度）',
  wm:'與手冊一致 ✅。<b>腦膜炎 200 mg/kg/day</b>（國際常用 200–300 mg/kg/day 分 Q6H）。每日 Max 12 g。新生兒優先於 ceftriaxone（不競爭膽紅素結合位）。',
  m:['腦膜炎 200 mg/kg/day 分 Q6H','每日 Max 12 g'],
  calc:bw=>[L('中度（每日）',MG(Math.min(100*bw,12000)),'分 Q6H = '+MG(Math.min(25*bw,3000))+'/次',100*bw>12000?'已達成人每日上限 12 g':null),
   L('重度（每日）',(100*bw>=12000)?MG(12000):rng(MG(Math.min(100*bw,12000)),MG(Math.min(150*bw,12000))),'分 Q6H',
     150*bw>12000?'已達成人每日上限 12 g':null),
   L('腦膜炎（每日）',MG(Math.min(200*bw,12000)),'分 Q6H',200*bw>12000?'已達每日 12 g 上限':null)]},
 {n:'Rocephin (ceftriaxone) IV',rt:'針劑',s:'ceftriaxone｜第三代 cephalosporin｜<b>vial 規格依院內</b>',f:'50–100 mg/kg/day Q12H 或 QD',
  w:'與手冊一致 ✅（中度 50–100、重度 100 mg/kg/day，單次 Max 1 g、重症 2 g）。<br><b>新生兒禁用或極度謹慎</b>：與膽紅素競爭白蛋白結合位，有<b>核黃疸</b>風險；且<b>不可與含鈣輸液併用</b>（會形成沈澱，已有致死案例）。另注意膽泥（biliary sludge）。',
  m:['腸炎 75–100 mg/kg/day','菌血症 / 腎盂腎炎 100 mg/kg/day','每日 Max 4 g'],
  calc:bw=>[L('中度（每日）',rng(MG(Math.min(50*bw,4000)),MG(Math.min(100*bw,4000))),'Q12H 或 QD',null),
   L('每次（Q12H）',MG(Math.min(50*bw,2000)),'',50*bw>2000?'已達單次 2 g':null),
   L('重度 / 腦膜炎（每日）',MG(Math.min(100*bw,4000)),'分 Q12H',100*bw>4000?'已達每日 4 g 上限':null)]},
 {n:'Cefixime (PO)',s:'cefixime｜第三代口服 cephalosporin｜<b>規格依院內</b>',f:'8 mg/kg/day，QD 或分 BID',
  wm:'與手冊一致 ✅。<b>Max 400 mg/day</b>。手冊另給固定劑量：BW &gt;25 kg 100 mg BID；BW &gt;40 kg 且嚴重感染 200 mg BID。<b>對 S. pneumoniae 涵蓋不佳</b>，AOM 不建議作第一線（第一線為 amoxicillin）。',
  m:['8 mg/kg/day，<b>Max</b> 400 mg/day','>25 kg：100 mg BID；>40 kg 重症：200 mg BID'],
  calc:bw=>{const d=Math.min(8*bw,400);
   return[L('每日總量',MG(d),'QD 或分 BID',8*bw>400?'已達每日上限 400 mg':null),
    L('BID 每次',MG(d/2),'',null)]}},
 {n:'Vancomycin IV',rt:'針劑',s:'vancomycin｜<b>vial 規格依院內</b>（常見 500 mg）｜抗 MRSA',f:'15 mg/kg/dose Q6H（= 60 mg/kg/day）',
  w:'與手冊一致 ✅。<b>必須監測 trough —— 於第四劑給藥前 30 分鐘抽血</b>，並持續監測腎功能。<br><b>輸注須 ≥60 分鐘</b>（每 500 mg 至少 30 分鐘），過快會引發 vancomycin infusion reaction（舊稱 red man syndrome）。中樞感染或重症可用至 60–80 mg/kg/day。',
  m:['15 mg/kg/dose Q6H','trough：第 4 劑前 30 分鐘','輸注 ≥60 分鐘；監測腎功能'],
  calc:bw=>{const d=Math.min(15*bw,1000);
   return[L('每次劑量',MG(d),'Q6H',15*bw>1000?'單次超過 1 g，請確認並延長輸注時間':null),
    L('每日總量',MG(Math.min(60*bw,4000)),'60 mg/kg/day',null)]}},
 {n:'Tazocin IV',rt:'針劑',s:'piperacillin/tazobactam 8:1｜<b>vial 規格依院內</b>',f:'112.5 mg/kg/dose Q8H（= PIP 300 mg/kg/day）',
  wm:'與手冊一致 ✅。單次 <b>Max 4500 mg Q8H</b>。<b>發熱性嗜中性球低下（neutropenic fever）之首選</b>。重症可考慮延長輸注（3–4 小時）以提高 T&gt;MIC。腎功能不全須調整。',
  m:['單次 <b>Max</b> 4500 mg','重症可延長輸注 3–4 小時'],
  calc:bw=>{const d=Math.min(112.5*bw,4500);
   return[L('每次劑量',MG(d),'Q8H',112.5*bw>4500?'已達單次上限 4500 mg':null),
    L('每日總量',MG(d*3),'（含 PIP + TAZ）',null)]}},
 {n:'Meropenem IV',rt:'針劑',s:'meropenem｜<b>vial 規格依院內</b>（常見 500 mg）｜carbapenem',f:'20 mg/kg/dose Q8H（= 60 mg/kg/day）',
  wm:'與手冊一致 ✅。<b>腦膜炎 120 mg/kg/day</b>（＝40 mg/kg/dose Q8H）。單次 Max 一般 1 g、腦膜炎 2 g。相較 imipenem <b>抽搐風險較低</b>，仍須注意癲癇病史者。屬廣效藥，應有明確適應症並及早降階。',
  m:['一般 20 mg/kg/dose Q8H','腦膜炎 40 mg/kg/dose Q8H','單次 Max 1 g（腦膜炎 2 g）'],
  calc:bw=>[L('一般每次',MG(Math.min(20*bw,1000)),'Q8H',20*bw>1000?'已達單次 1 g':null),
   L('腦膜炎每次',MG(Math.min(40*bw,2000)),'Q8H',40*bw>2000?'已達單次 2 g':null)]},
]},

{c:'流感抗病毒 Influenza antivirals',k:'流感 influenza 流感抗病毒 antiviral 克流感 tamiflu oseltamivir 紓伏效 xofluza baloxavir 瑞貝塔 rapiacta peramivir 神經胺酸酶 抑制劑',d:[
 {n:'Tamiflu (oseltamivir)',rt:'口服',s:'oseltamivir 75 mg/膠囊｜克流感｜院內以膠囊泡水分裝，處方以顆數開立',f:'體重分級 BID × 5 天 → ÷75 ＝ 顆數',
  w:'<b>&lt;1 歲的劑量有兩套並存</b>：CDC／AAP 為 <b>3 mg/kg/dose BID</b>（本卡採用，見下方附註列），台灣仿單與疾管署另用固定 mg 分級（&lt;3 個月 12 mg、3–5 個月 20 mg、6–11 個月 25 mg）—— 差距在 3 個月以下最大，<b>依院內共識擇一，勿混用</b>。<b>早產兒不可套用足月兒劑量</b>：矯正年齡 PMA &lt;38 週 <b>1 mg/kg</b>、38–40 週 <b>1.5 mg/kg</b>、&gt;40 週才是 3 mg/kg（腎清除率未成熟）。',
  wm:'<b>48 小時內投藥</b>效果最好，但<b>重症或高風險族群即使超過 48 小時仍應治療</b>，不要因為超時而不給。腎功能不全須減量。',
  m:['體重分級（≥1 歲）：≤15 kg 30 mg／&gt;15–23 kg 45 mg／&gt;23–40 kg 60 mg／&gt;40 kg 75 mg，皆 BID','分級劑量除以 75 剛好是整齊的顆數：<b>0.4／0.6／0.8／1 顆</b>','<b>預防性投藥</b>：同一分級劑量改 <b>QD × 7–10 天</b>（顆數不變，次數減半）','<b>泡製方式與濃度由藥局決定</b> —— 處方只開顆數，不需指定 mL','公費適用條件依疾管署當年度公告，本頁不記錄'],
  r:[['CDC: Influenza Antiviral Medications in Children','https://www.cdc.gov/flu/treatment/children-antiviral.html'],['AAP 2023–2024 Influenza Recommendations','https://publications.aap.org/pediatrics/article/152/4/e2023063772/193776/Recommendations-for-Prevention-and-Control-of']],
  calc:bw=>{const band=bw<=15?30:bw<=23?45:bw<=40?60:75,cap=band/75,inf=3*bw;
   return[L('每次劑量',MG(band),'BID × 5 天',bw<=12?'若<b>未滿 1 歲</b>，請改用下方 3 mg/kg 的數字，不要用分級劑量':null),
    L('開立顆數',num(r2(cap))+' 顆','（75 mg/膠囊）BID × 5 天',null),
    S('療程總需',num(r2(cap*10))+' 顆','（每日 '+num(r2(cap*2))+' 顆 × 5 天）'),
    L('預防性投藥',MG(band),'QD × 7–10 天（暴露後）',null),
    S('　預防用顆數',num(r2(cap))+' 顆','QD；7 天療程共 '+num(r2(cap*7))+' 顆'),
    /* 3 mg/kg 只在可能未滿 1 歲的體重才顯示 —— 25 kg 的孩子看到這一列只會混淆 */
    ...(bw<=15?[S('未滿 1 歲：3 mg/kg/dose',MG(inf)+' <small>（'+num(r2(inf/75))+' 顆）</small>','BID —— 早產兒另計，見上方警語')]:[])]}},
 {n:'Xofluza (baloxavir)',rt:'口服',s:'baloxavir marboxil 20 mg/錠｜紓伏效｜衛部藥輸字第027693號',f:'單次口服一劑即完成療程',
  w:'<b>限 ≥5 歲且 ≥20 kg</b>（治療與暴露後預防皆同）。<b>&lt;20 kg 的劑量是 2 mg/kg，需顆粒／懸液劑型；台灣目前只有 20 mg 膜衣錠，給不到 —— 請改用 Tamiflu。</b>',
  wm:'<b>單次投藥即完成療程，不可再補第二劑</b>。與含<b>多價陽離子</b>的制酸劑、乳製品、鈣／鎂／鐵補充劑同服會顯著降低吸收，應錯開。',
  m:['<b>20–&lt;80 kg：40 mg</b>（20 mg × 2 錠）','<b>≥80 kg：80 mg</b>（20 mg × 4 錠）','48 小時內投藥','公費適用條件依疾管署當年度公告，本頁不記錄'],
  r:[['紓伏效膜衣錠 20 毫克 台灣仿單（塩野義）','https://www.shionogi.com/content/dam/shionogi/ts/products/pdf/XOFLUZA%20PI%20v4-1130509.pdf']],
  calc:bw=>{if(bw<20)return[L('劑量','不適用','單次口服',
     '體重 &lt;20 kg 不在適應症內，且台灣無 2 mg/kg 的顆粒劑型 —— 請改用 Tamiflu'),
    S('適應症範圍','≥5 歲且 ≥20 kg','年齡與體重<b>兩個條件都要滿足</b>')];
   const mg=bw<80?40:80;
   return[L('劑量',MG(mg),'單次口服，療程即完成',null),
    S('錠數',(mg/20)+' 錠','（20 mg/錠）'),
    S('適應症範圍','≥5 歲且 ≥20 kg','20–&lt;80 kg 40 mg；≥80 kg 80 mg')]}},
 {n:'Rapiacta (peramivir)',rt:'針劑',s:'peramivir 300 mg/60 mL/袋（5 mg/mL）｜瑞貝塔｜衛部藥輸字第026649號｜院內品項為袋裝',f:'(BW×10) mg IV，Max 600 mg',
  w:'<b>點滴靜脈注射需 ≥15 分鐘</b>，不可推注。適用 <b>≥1 個月</b>。兒童 <b>10 mg/kg、單次 ≤600 mg</b>；成人為固定 <b>300 mg</b>（重症可至 600 mg），<b>成人不是以體重計算</b>。',
  wm:'定位是<b>無法口服或吸收不良</b>時的替代 —— 能口服就用 Tamiflu，靜脈給藥沒有療效優勢。48 小時內投藥；重症可連續多日給藥。腎功能不全須減量。',
  m:['<b>院內用袋裝：1 袋 ＝ 300 mg/60 mL ＝ 5 mg/mL</b>，處方以袋數開立','<b>未滿 1 袋不要給整袋</b> —— 依「輸注量」的 mL 數給，剩餘丟棄','另有 150 mg 瓶裝規格，濃度與袋裝不同；若拿到非袋裝品項務必重新核算','公費適用條件依疾管署當年度公告，本頁不記錄'],
  r:[['Rapiacta 台灣產品頁（塩野義）','https://www.shionogi.com/tw/zh/products/yes/prescription/rapiacta.html']],
  calc:bw=>{const raw=10*bw,mgv=Math.min(raw,600),bags=Math.ceil(mgv/300);
   /* 10 mg/kg 在 30 kg 就追過成人的固定 300 mg —— 體型接近成人時不該再往上加 */
   const flag=raw>600?'已達單次上限 600 mg（算出 '+MG(raw)+'）'
     :raw>300?'10 mg/kg 從 <b>30 kg</b> 起就超過成人的固定 300 mg。兒童仍依 10 mg/kg，但<b>已達成人體型者請先確認要用哪一種</b> —— 成人 300 mg ＝ 1 袋':null;
   return[L('兒童劑量',MG(mgv),'IV drip ≥15 分鐘，單次',flag),
    L('開立袋數',bags+' 袋','（1 袋 ＝ 300 mg/60 mL）',null),
    S('實際輸注量',mL2(mgv/5),'（5 mg/mL；'+(mgv<300?'未滿 1 袋，依此 mL 數給，餘量丟棄':'袋數 ×60 mL')+'）'),
    S('成人劑量','300 mg','不依體重；重症可至 600 mg')]}},
]},

{c:'耳鼻眼 局部用藥',k:'耳滴劑 眼藥水 otitis 結膜炎 ear eye',d:[
 {n:'Tarivid otic soln',rt:'外用',s:'ofloxacin 0.3% 耳滴劑',f:'依適應症：AOM w/ tube 5 gtt BID｜外耳炎 5 gtt QD',
  wm:'<b>BID 只適用於「1–12 歲、有中耳通氣管的 AOM」</b>；<b>外耳炎為 5 滴 QD</b>。',
  m:['<b>無耳毒性</b>，有裝 tube 或 rupture 時仍可用'],calc:null},
 {n:'Mycomb',rt:'外用',s:'triamcinolone 1 + neomycin 2.5 + gramicidin 0.25 mg/mL + nystatin｜耳滴劑',f:'2 gtt TID（限外耳炎且鼓膜完整）',
  w:'含 neomycin（胺基醣苷）→ <b>鼓膜穿孔或已置中耳通氣管者可致不可逆的耳蝸 / 前庭毒性，即永久性聽力喪失</b>。<b>鼓膜完整性不明時一律改用 ofloxacin（Tarivid）</b>。',
  m:['僅能用於外耳炎，且需確認鼓膜完整'],calc:null},
 {n:'Sinomin / O.S.M.D.',rt:'外用',s:'sulfamethoxazole 40 mg/mL 點眼液',f:'1–2 gtt QID',
  w:'<b>磺胺過敏者（含全身性磺胺過敏）禁用</b>，有 <b>SJS / TEN 交叉反應</b>風險。細菌性結膜炎實證首選仍為 aminoglycoside / macrolide / fluoroquinolone。蠶豆症禁用。',
  m:['蠶豆症<b>禁用</b>'],calc:null},
 {n:'Zaditen',rt:'外用',s:'ketotifen 0.025% 點眼液｜>3 y',f:'1 gtt BID',m:[],calc:null},
]},

{c:'皮膚癢 / 蕁麻疹',k:'皮膚癢 蕁麻疹 dermatitis urticaria 濕疹',d:[
 {n:'C.B. Strong',rt:'外用',s:'外用｜<b>學名與含量待核</b>',f:'PRN',
  m:['含 camphor，蠶豆症<b>禁用</b>'],calc:null},
 {n:'Menphencala',rt:'外用',s:'calamine 8% + zinc oxide 8% 洗劑',f:'PRN',
  m:['收斂效果，可能造成皮膚乾癢'],calc:null},
 {n:'Solaxin',s:'chlorzoxazone 200 mg/錠｜中樞作用骨骼肌鬆弛劑',f:'20 mg/kg/day 或 600 mg/m²/day',
  w:'<b>藥理上不該用於腹痛 / 腸絞痛</b> —— 這是<b>中樞作用的骨骼肌鬆弛劑，對胃腸道平滑肌無作用</b>。且有<b>特異體質性、可致命的肝毒性</b>，肝功能不全兒童為禁忌。胃腸絞痛請改用 hyoscine butylbromide（Buscopan）。劑量數值本身 20 mg/kg/day 正確 ✅',
  m:['分 3–4 次','成人 250–750 mg TID–QID'],
  calc:bw=>[L('每日總量',MG(20*bw),'分 3–4 次',null),L('每次劑量',rng(MG(20*bw/4),MG(20*bw/3)),'',null)]},
]},

{c:'其他 Others',k:'顯影劑 urograffin UGI 上消化道攝影 鋇 barium iohexol omnipaque',d:[
 {n:'Urograffin 口服 UGI',s:'diatrizoate｜離子型高滲透壓顯影劑｜<b>濃度依品項</b>',f:'兒科不建議口服使用',
  w:'<b>兒科明文不建議口服。</b>Applied Radiology 兒科螢光透視專論原文指出 diatrizoate 水溶液<b>絕不可經口給予兒科病人</b>。Gastrografin 仿單警語：誤吸可致<b>肺水腫、肺炎、死亡</b>；幼小或衰弱兒童可因血漿體液流失導致<b>類休克狀態</b>。<b>3 倍稀釋並不足夠</b> —— 原液約 1900–2100 mOsm/kg，稀釋後仍約 600–700，遠高於血漿的 290。',
  m:['<b>常規 UGI</b>：改用硫酸鋇 (barium sulfate)',
     '<b>疑穿孔 / 廔管 / 高吸入風險</b>：改用低滲透壓非離子型 iohexol (Omnipaque 180–240)'],
  r:[['Applied Radiology 兒科顯影劑選擇','https://appliedradiology.com/articles/selecting-contrast-media-for-pediatric-fluoroscopy-a-primer'],['Gastrografin ISI','https://www.bracco.com/sites/default/files/2024-10/us-en-2024-10-02-isi-gastrografin.pdf']],
  calc:null},
]},

{c:'急救藥物 Emergency',k:'急救 code CPR PALS 插管 鎮靜 心律不整 emergency resuscitation',d:[
 {n:'★ Epinephrine (Adrenalin)',rt:'針劑',s:'epinephrine 1 mg/mL (1:1000)｜1 mL/amp',f:'IV/IO 0.01 mg/kg（＝1:10,000 稀釋液 0.1 mL/kg）',
  wm:'與手冊一致 ✅。給藥後<b>務必以 N/S 5 mL 沖管</b>。IV 用的是 <b>1:10,000</b>（原液 1 mL 加 N/S 9 mL 稀釋成 10 mL）；<b>ET 才用未稀釋的 1:1000</b> —— 兩者濃度差 10 倍，是急救時最典型的給藥錯誤。',
  m:['IV/IO：Q3–5 分鐘可重複','ET：僅在無血管路徑時使用，之後盡快建立 IO'],
  calc:bw=>{const iv=Math.min(0.01*bw,1),et=Math.min(0.1*bw,2.5);
   return[L('IV / IO 劑量',MG(iv),'Q3–5 min',0.01*bw>1?'已達單次上限 1 mg':null),
    L('抽取量（1:10,000）',mL(iv/0.1),'稀釋後濃度 0.1 mg/mL',null),
    L('ET 劑量',MG(et),'（1:1000 原液）',0.1*bw>2.5?'已達 ET 上限 2.5 mg':null),
    L('ET 抽取量（1:1000）',mL(et),'原液，勿稀釋',null)]}},
 {n:'★ Atropine',rt:'針劑',s:'atropine sulfate｜<b>台灣有 0.5 與 1 mg/mL 兩種規格</b>',f:'IV/IO 0.02 mg/kg',
  wm:'<b>最低劑量規定已有變動</b>：AHA PALS 自 2015 年起<b>不再規定 0.1 mg 最低劑量</b>（原下限源自「低劑量致反常性心搏過緩」的疑慮，後續證據不支持），北醫手冊仍載此下限，部分參考書亦保留 —— 兩種寫法都能查到，依院內共識為準。劑量本體 0.02 mg/kg 無爭議，<b>單次上限 0.5 mg</b>（青少年 1 mg），必要時可重複一次。<br><b>濃度須核對</b>：台灣 atropine 注射液有 0.05%（0.5 mg/mL）與 1 mg/mL 兩種許可證，手冊寫 1 mg/1 mL，抽藥前務必看安瓿標示。',
  m:['0.02 mg/kg，<b>單次 Max 0.5 mg</b>（青少年 1 mg）','可重複一次；<b>無最低劑量下限</b>','適應症：迷走神經性心搏過緩、插管前給藥、有機磷中毒'],
  calc:bw=>{const raw=0.02*bw,d=Math.min(raw,0.5);
   return[L('劑量',MG(d),'IV / IO',raw>0.5?'已達單次上限 0.5 mg（算出 '+MG(raw)+'）':null),
    L('抽取量（1 mg/mL）',mL(d),'',null),
    L('抽取量（0.5 mg/mL）',mL(d/0.5),'',null)]}},
 {n:'Dormicum (midazolam)',rt:'針劑',s:'midazolam｜<b>台灣有 1 與 5 mg/mL 兩種規格</b>',f:'IV 0.05–0.1 mg/kg 緩推｜IM 0.1–0.15 mg/kg',
  w:'<b>⚠ 兩種濃度差 5 倍</b>：台灣 midazolam 注射液有 1 mg/mL（南光美得定）與 5 mg/mL（聯邦優靜眠）兩種許可證，抽藥前務必核對安瓿。<br>IV <b>須緩推 2–3 分鐘</b>，快推會呼吸抑制。累積上限 <b>0.6 mg/kg 或 10 mg</b>（與手冊一致 ✅）。給藥時<b>須備妥 flumazenil、bag-mask 與監測</b>。',
  m:['IV 0.05–0.1 mg/kg 緩推 2–3 分鐘，可每 2–3 分鐘重複','IM 0.1–0.15 mg/kg','<b>累積 Max</b> 0.6 mg/kg 或 10 mg'],
  calc:bw=>{const lo=0.05*bw,hi=0.1*bw,cap=Math.min(0.6*bw,10);
   return[L('IV 單次',rng(MG(lo),MG(hi)),'緩推 2–3 分鐘',null),
    L('IM 單次',rng(MG(0.1*bw),MG(0.15*bw)),'',null),
    L('累積上限',MG(cap),'0.6 mg/kg 或 10 mg，取小者',null),
    L('抽取量（5 mg/mL）',rng(mL(lo/5),mL(hi/5)),'IV 單次',null)]}},
 {n:'★ Adenosine',rt:'針劑',s:'adenosine 3 mg/mL（6 mg/2 mL/amp）',f:'第一劑 0.1 mg/kg｜第二劑 0.2 mg/kg',
  wm:'手冊表列第一劑，此處補上第二劑：SVT 若第一劑無效，<b>第二劑加倍為 0.2 mg/kg（Max 12 mg）</b>。<br>半衰期不到 10 秒，<b>必須從最靠近心臟的大靜脈以雙針筒法極速推注，並立刻以 N/S 5–10 mL 沖管</b>，推慢了等於沒給。給藥時須<b>接上心電圖連續記錄</b>。',
  m:['第一劑 0.1 mg/kg，<b>Max 6 mg</b>','第二劑 0.2 mg/kg，<b>Max 12 mg</b>','極速推注 + 立即沖管；氣喘為相對禁忌'],
  calc:bw=>{const d1=Math.min(0.1*bw,6),d2=Math.min(0.2*bw,12);
   return[L('第一劑',MG(d1),'快速 IV push',0.1*bw>6?'已達上限 6 mg':null),
    L('抽取量',mL(d1/3),'（3 mg/mL）',null),
    L('第二劑（無效時）',MG(d2),'快速 IV push',0.2*bw>12?'已達上限 12 mg':null),
    L('抽取量',mL(d2/3),'（3 mg/mL）',null)]}},
 {n:'★ Amiodarone (Cordarone)',rt:'針劑',s:'amiodarone HCl 150 mg/3 mL/amp',f:'依有無脈搏分流 —— 見下',
  wm:'劑量 5 mg/kg 與手冊一致 ✅，此處補上<b>給藥速度依有無脈搏而不同</b>（手冊表格未列）：<br><b>無脈搏（VF / 無脈性 VT）</b>：5 mg/kg <b>快速推注</b>，可重複至每日 15 mg/kg。<br><b>有脈搏之心搏過速</b>：同樣 5 mg/kg，但<b>須輸注 20–60 分鐘</b> —— 快推會造成低血壓與房室傳導阻斷。<br>單次上限 300 mg。須連續心電圖與血壓監測，並會診小兒心臟科。',
  m:['無脈搏：5 mg/kg 快推，可重複，每日 Max 15 mg/kg','有脈搏：5 mg/kg 輸注 20–60 分鐘','單次 <b>Max</b> 300 mg'],
  calc:bw=>{const d=Math.min(5*bw,300);
   return[L('單次劑量',MG(d),'兩種情境同劑量',5*bw>300?'已達單次上限 300 mg':null),
    L('抽取量',mL(d/50),'（150 mg/3 mL = 50 mg/mL）',null),
    L('每日上限',MG(Math.min(15*bw,2200)),'15 mg/kg/day',null)]}},
 {n:'Dopamine (Uramin)',rt:'針劑',s:'dopamine 200 mg/5 mL/amp',f:'2–20 µg/kg/min 連續輸注',
  wm:'低劑量 2–10、高劑量 10–20 µg/kg/min（與手冊一致 ✅）。所謂「腎劑量 dopamine」<b>已無證據支持，不應為了保腎而使用</b>。須<b>經中心靜脈給藥</b>；外滲會造成組織壞死（解藥為 phentolamine 局部浸潤）。',
  m:['須連續輸注並監測血壓','外滲風險高，優先走中心靜脈'],
  calc:bw=>[L('低劑量範圍',num(r2(2*bw*60/1000))+' ~ '+num(r2(10*bw*60/1000))+' mg/hr','2–10 µg/kg/min',null),
   L('高劑量範圍',num(r2(10*bw*60/1000))+' ~ '+num(r2(20*bw*60/1000))+' mg/hr','10–20 µg/kg/min',null),
   L('每分鐘 µg 量',num(r1(2*bw))+' ~ '+num(r1(20*bw))+' µg/min','（供配液計算）',null)]},
 {n:'Propofol',rt:'針劑',s:'propofol 10 mg/mL（200 mg/20 mL/amp）',f:'誘導 2–3 mg/kg｜鎮靜 1–2 mg/kg',
  wm:'<b>與手冊數字有落差，請以院內共識為準。</b>手冊表列 IV 0.2 mg/kg；國際標準兒童（3–16 歲）靜脈誘導為 <b>2–3 mg/kg</b>，程序性鎮靜 1–2 mg/kg，下方依後者計算。0.2 mg/kg 低於一般追加劑量，開立前請確認情境。<br><b>兒童禁止長時間輸注鎮靜</b>（propofol infusion syndrome：代謝性酸中毒、橫紋肌溶解、心衰竭）。須由具氣道處理能力者給藥並全程監測。',
  m:['誘導 2–3 mg/kg IV','程序性鎮靜 1–2 mg/kg','<b>勿用於 PICU 長時間鎮靜</b>'],
  calc:bw=>[L('誘導劑量',rng(MG(2*bw),MG(3*bw)),'IV',null),
   L('抽取量',rng(mL(2*bw/10),mL(3*bw/10)),'（10 mg/mL）',null),
   L('鎮靜劑量',rng(MG(bw),MG(2*bw)),'IV',null)]},
 {n:'Aminophylline',rt:'針劑',s:'aminophylline 25 mg/mL（250 mg/10 mL/amp）',f:'Loading 5–6 mg/kg｜維持依年齡',
  wm:'手冊 loading 3 mg/kg 屬<b>保守取法</b>（近期已用過 theophylline 者本就減半），標準為 <b>5–6 mg/kg 輸注 20–30 分鐘</b>，下方兩者並列。<br>維持量<b>依年齡差異大</b>：1–9 歲約 1.0 mg/kg/hr（≈24 mg/kg/day）、9–12 歲約 0.9、青少年約 0.7（≈17）—— 手冊的 12 mg/kg/day 接近青少年端，用於幼兒偏低。<b>治療區間窄，須驗血中濃度</b>（目標 10–20 µg/mL）。現行氣喘指引已不將 aminophylline 列為第一線。',
  m:['Loading 5–6 mg/kg 輸注 20–30 分鐘（手冊 3 mg/kg 為保守取法）','維持量依年齡調整並驗濃度','中毒表現：嘔吐、心搏過速、抽搐'],
  calc:bw=>[L('Loading（標準 5–6 mg/kg）',rng(MG(5*bw),MG(6*bw)),'輸注 20–30 分鐘',null),
   L('Loading（手冊 3 mg/kg）',MG(3*bw),'輸注 20–30 分鐘',null),
   L('抽取量（標準）',rng(mL(5*bw/25),mL(6*bw/25)),'（25 mg/mL）',null),
   L('維持（1–9 歲，1.0 mg/kg/hr）',MG(bw)+'/hr','≈ '+MG(24*bw)+'/day',null),
   L('維持（青少年，0.7 mg/kg/hr）',MG(0.7*bw)+'/hr','≈ '+MG(16.8*bw)+'/day',null)]},
 {n:'Solu-Tisone (hydrocortisone)',rt:'針劑',s:'hydrocortisone sodium succinate 100 mg/amp',f:'依適應症分流 —— 見下',
  wm:'<b>與手冊數字有落差，請以院內共識為準。</b>經 TFDA 查證本品為 hydrocortisone（衛署藥製字，100 mg/amp）。手冊表列 IM 0.3–0.6 mg/kg，該級距與 betamethasone／dexamethasone（見哮吼段 Rinderon）相同，而 hydrocortisone <b>效價低約 25–30 倍</b>，若情境為急救則明顯偏低。<br>國際劑量依適應症：<b>腎上腺危象</b> 2 mg/kg（或 50–100 mg/m²）IV bolus；<b>重積氣喘</b> 4–8 mg/kg/dose Q6H；<b>過敏性休克輔助</b> 4–8 mg/kg，Max 250 mg（且<b>類固醇不是過敏性休克的第一線 —— 第一線是 IM epinephrine</b>）。下方依國際劑量計算。',
  m:['腎上腺危象：2 mg/kg IV bolus','重積氣喘：4–8 mg/kg/dose Q6H','過敏性休克輔助：4–8 mg/kg，Max 250 mg'],
  calc:bw=>[L('腎上腺危象',MG(2*bw),'IV bolus',null),
   L('氣喘 / 過敏（每次）',rng(MG(Math.min(4*bw,250)),MG(Math.min(8*bw,250))),'Q6H',8*bw>250?'已達單次上限 250 mg':null),
   L('抽取量（100 mg/amp 溶後）',rng(num(r2(Math.min(4*bw,250)/100)),num(r2(Math.min(8*bw,250)/100)))+' amp','',null)]},
 {n:'Sodium bicarbonate (Rolikan)',rt:'針劑',s:'sodium bicarbonate 8.4% = 1 mEq/mL',f:'半矯正：0.3 × BW × (−BE) × 0.5 mEq',
  wm:'公式與手冊一致 ✅（0.3 × 體重 × 鹼缺失 × 0.5，先給半量再驗血）。心跳停止時的經驗劑量為 <b>1 mEq/kg</b>。<b>新生兒與嬰兒須稀釋成 4.2%（1:1 加注射用水）</b>再給，原液高滲透壓有腦室內出血風險。<b>給藥前必須先確保換氣足夠</b> —— 通氣不足時給碳酸氫鈉反而加重細胞內酸中毒。勿與含鈣輸液同管。',
  m:['心跳停止：1 mEq/kg','代謝性酸中毒：依 BE 半矯正公式','嬰兒須稀釋為 4.2%'],
  calc:bw=>[L('心跳停止經驗劑量',num(r1(bw))+' mEq','= '+mL(bw)+'（8.4% 原液）',null),
   L('BE −10 時之半矯正量',num(r1(0.3*bw*10*0.5))+' mEq','公式：0.3 × BW × (−BE) × 0.5',null),
   L('BE −5 時之半矯正量',num(r1(0.3*bw*5*0.5))+' mEq','',null)]},
 {n:'Digoxin (Lanoxin)',rt:'針劑',s:'digoxin 0.25 mg/mL（0.5 mg/2 mL/amp）',f:'不提供單一數值 —— 須查年齡別表',
  wm:'本卡片<b>刻意不提供體重換算</b>。Digoxin 的數位化總量（TDD）<b>隨年齡差異極大</b>（早產兒、足月兒、嬰兒、兒童、青少年各不相同），分次給法為 ½ → ¼ → ¼，維持量另計並須依腎功能調整。台灣仿單即載明「劑量需依個人年齡、精瘦體重及腎功能而裁定」。<b>治療區間極窄</b>，給單一 mg/kg 數字比不給更容易出錯，請查年齡別劑量表並會診小兒心臟科。口服改靜脈須減量約 33%。',
  m:['本卡片<b>刻意不做體重換算</b>','須查年齡別 TDD 表並會診','注意低血鉀會加重毒性'],
  calc:null},
]},
];


window.PEDS_DATA = DATA;
const TOCGROUPS=[
  {g:'',        idx:[0,12,13,17]},         /* 退燒、抗生素、流感抗病毒、急救藥物 */
  {g:'呼吸道症狀', idx:[1,2,3,4,5,6]},        /* 止咳 化痰 鼻塞 喉嚨痛 哮吼 氣喘 */
  {g:'腸胃症狀',   idx:[7,8,9,10,11]},        /* 腹瀉 便秘 功能性腹痛 嘔吐 上腹痛 */
  {g:'其他',      idx:[14,15,16]},           /* 耳鼻眼 皮膚癢 其他 */
];
window.PEDS_TOC = TOCGROUPS;
